spring:
  application:
    name: delta-calcite
  main:
    web-application-type: none
grpc:
  server:
    address: '*'
    port: 8080
    security:
      enabled: false
  client:
    hello:
      address: "localhost:8080"
      negotiation-type: plaintext
calcite:
  connection:
    quoting: BACK_TICK
    caseSensitive: true
    unquotedCasing: UNCHANGED