grpc:
  server:
    security:
      enabled: false
mill:
  backend:
    provider: jdbc
    connection:
      quoting: BACK_TICK
      caseSensitive: true
      unquotedCasing: UNCHANGED
    jdbc:
      url: "jdbc:h2:mem:test;INIT=RUNSCRIPT FROM './test/datasets/users/sql/users.sql'"
      driver: "org.h2.Driver"
      username: "*"
      password: "*"
      target-schema: "ts"

