name: ${schema_name}
storage:
  type: adls
  endpoint: https://${storage_account_name}.blob.core.windows.net
  container: ${container_name}
  auth:
    preferAmbientCredentials: true
conflicts: reject
readers:
  - type: parquet
    table:
      mapping:
        type: regex
        pattern: "(?<table>[^/]+)/[^/]+\\.parquet$"
        tableNameGroup: table
  - type: csv
    format:
      delimiter: ";"
      hasHeader: true
      skipEmptyLines: true
    table:
      mapping:
        type: regex
        pattern: "(?<table>[^/]+)/[^/]+\\.csv$"
        tableNameGroup: table
  - type: avro
    table:
      mapping:
        type: regex
        pattern: "(?<table>[^/]+)/[^/]+\\.avro$"
        tableNameGroup: table
  - type: excel
    format:
      hasHeader: true
      sheetIndex: 0
    table:
      mapping:
        type: regex
        pattern: "(?<table>[^/]+)/[^/]+\\.xlsx$"
        tableNameGroup: table
