-- Reference copy of persistence/mill-persistence/.../V4__metadata_greenfield.sql (keep in sync).
-- Data rows for metadata_scope and facet types are never inserted here — use mill.metadata.seed.resources.

-- V4__metadata_greenfield.sql — squashed metadata schema (WI-122). Fresh DB after V1–V3 only.

CREATE TABLE metadata_scope (
    scope_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36)  NOT NULL,
    scope_res        VARCHAR(512) NOT NULL,
    scope_type       VARCHAR(32)  NOT NULL,
    reference_id     VARCHAR(255),
    display_name     VARCHAR(512),
    owner_id         VARCHAR(255),
    visibility       VARCHAR(32)  NOT NULL DEFAULT 'PUBLIC',
    created_at       TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    last_modified_at TIMESTAMP    NOT NULL,
    last_modified_by VARCHAR(255),
    CONSTRAINT uq_metadata_scope_res UNIQUE (scope_res),
    CONSTRAINT uq_metadata_scope_uuid UNIQUE (uuid)
);

-- metadata_scope rows: load only via mill.metadata.seed.resources (e.g. metadata/platform-bootstrap.yaml).

CREATE TABLE metadata_entity (
    entity_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36)  NOT NULL,
    entity_res       VARCHAR(512) NOT NULL,
    entity_kind      VARCHAR(255),
    created_at       TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    last_modified_at TIMESTAMP    NOT NULL,
    last_modified_by VARCHAR(255),
    CONSTRAINT uq_metadata_entity_res UNIQUE (entity_res),
    CONSTRAINT uq_metadata_entity_uuid UNIQUE (uuid)
);

CREATE TABLE metadata_facet_type_def (
    def_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36)  NOT NULL,
    type_res         VARCHAR(512) NOT NULL,
    manifest_json    TEXT         NOT NULL,
    mandatory        BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    last_modified_at TIMESTAMP    NOT NULL,
    last_modified_by VARCHAR(255),
    CONSTRAINT uq_metadata_facet_type_def_res UNIQUE (type_res),
    CONSTRAINT uq_metadata_facet_type_def_uuid UNIQUE (uuid)
);

CREATE TABLE metadata_facet_type (
    facet_type_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36)  NOT NULL,
    type_res         VARCHAR(512) NOT NULL,
    slug             VARCHAR(512),
    display_name     VARCHAR(512),
    description      TEXT,
    source           VARCHAR(32)  NOT NULL DEFAULT 'OBSERVED',
    def_id           BIGINT,
    created_at       TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    last_modified_at TIMESTAMP    NOT NULL,
    last_modified_by VARCHAR(255),
    CONSTRAINT uq_metadata_facet_type_res UNIQUE (type_res),
    CONSTRAINT uq_metadata_facet_type_uuid UNIQUE (uuid),
    CONSTRAINT fk_metadata_facet_type_def FOREIGN KEY (def_id) REFERENCES metadata_facet_type_def (def_id) ON DELETE SET NULL
);

CREATE TABLE metadata_entity_facet (
    facet_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36)  NOT NULL,
    entity_id        BIGINT       NOT NULL,
    facet_type_id    BIGINT       NOT NULL,
    scope_id         BIGINT       NOT NULL,
    payload_json     TEXT         NOT NULL DEFAULT '{}',
    merge_action     VARCHAR(32)  NOT NULL DEFAULT 'SET',
    created_at       TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    last_modified_at TIMESTAMP    NOT NULL,
    last_modified_by VARCHAR(255),
    CONSTRAINT uq_metadata_entity_facet_uuid UNIQUE (uuid),
    CONSTRAINT fk_mef_entity FOREIGN KEY (entity_id) REFERENCES metadata_entity (entity_id) ON DELETE CASCADE,
    CONSTRAINT fk_mef_facet_type FOREIGN KEY (facet_type_id) REFERENCES metadata_facet_type (facet_type_id),
    CONSTRAINT fk_mef_scope FOREIGN KEY (scope_id) REFERENCES metadata_scope (scope_id) ON DELETE CASCADE
);

CREATE INDEX idx_metadata_entity_facet_entity ON metadata_entity_facet (entity_id);
CREATE INDEX idx_metadata_entity_facet_type ON metadata_entity_facet (facet_type_id);
CREATE INDEX idx_metadata_entity_facet_scope ON metadata_entity_facet (scope_id);
CREATE INDEX idx_metadata_entity_facet_triple ON metadata_entity_facet (entity_id, facet_type_id, scope_id);

CREATE TABLE metadata_audit (
    audit_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation        VARCHAR(64)  NOT NULL,
    subject_type     VARCHAR(32)  NOT NULL,
    subject_ref      VARCHAR(512),
    actor_id         VARCHAR(255),
    correlation_id   VARCHAR(255),
    occurred_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payload_before   TEXT,
    payload_after    TEXT
);

CREATE INDEX idx_metadata_audit_subject ON metadata_audit (subject_ref);
CREATE INDEX idx_metadata_audit_occurred ON metadata_audit (occurred_at);
CREATE INDEX idx_metadata_audit_actor ON metadata_audit (actor_id);
CREATE INDEX idx_metadata_audit_operation ON metadata_audit (operation);

CREATE TABLE metadata_seed (
    ledger_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36)  NOT NULL,
    seed_key         VARCHAR(512) NOT NULL,
    completed_at     TIMESTAMP,
    fingerprint      VARCHAR(512),
    last_error       TEXT,
    created_at       TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    last_modified_at TIMESTAMP    NOT NULL,
    last_modified_by VARCHAR(255),
    CONSTRAINT uq_metadata_seed_key UNIQUE (seed_key),
    CONSTRAINT uq_metadata_seed_uuid UNIQUE (uuid)
);

-- Facet type definitions + runtime rows: load only via mill.metadata.seed.resources (FacetCatalog.registerDefinition).
