stages:
  - build
  - integration
  - publish
  - release

variables:
  RUN_INTEGRATION: 
    value: "false"
    description: "Set to true to run integration tests"
    options:
      - "true"
      - "false"
  RUN_PUBLISH:
    value: "false"
    description: "Publish include control: auto (protected only), true (force), false (disable)"
    options:
      - "auto"
      - "true"
      - "false"
  RUN_FULL_TEST:
    value: "false"
    description: "Full non-integration test pipeline control: auto (MR/protected branch), true (force), false (disable)"
    options:
      - "auto"
      - "true"
      - "false"
  GRADLE_CONTINUE:
    value: "false"
    description: "Set to true to continue Gradle build after failure"
    options:
      - "true"
      - "false"
  GRADLE_FORCE_CLEAN:
    value: "false"
    description: "Set to true to force Gradle clean"
    options:
      - "true"
      - "false"


  

workflow:
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
      when: always
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED != "true"'
      when: never
    - when: always


.if-protected: &if-protected
  if: '$CI_COMMIT_REF_PROTECTED == "true"'

.if-mr-full: &if-mr-full
  if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "rc" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")'

.if-run-integration: &if-run-integration
  if: '$RUN_INTEGRATION == "true"'

.build-changes: &build-changes
  changes:
    - .gitlab-ci.yml
    - .gitlab/**/*    
    - build-logic/**/*

include:
  - local: ${CI_PROJECT_DIR}/.gitlab/common/common.yml
  - local: ${CI_PROJECT_DIR}/core/.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_REF_PROTECTED != "true" && $CI_PIPELINE_SOURCE != "merge_request_event" && $RUN_INTEGRATION != "true" && $RUN_FULL_TEST != "true"'
        changes:
          - core/**/*
        when: always 
      - when: never
      
  - local: ${CI_PROJECT_DIR}/metadata/.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_REF_PROTECTED != "true" && $CI_PIPELINE_SOURCE != "merge_request_event" && $RUN_INTEGRATION != "true" && $RUN_FULL_TEST != "true"'
        changes:
          - metadata/**/*
        when: always
      - when: never

  - local: ${CI_PROJECT_DIR}/persistence/.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_REF_PROTECTED != "true" && $CI_PIPELINE_SOURCE != "merge_request_event" && $RUN_INTEGRATION != "true" && $RUN_FULL_TEST != "true"'
        changes:
          - persistence/**/*
        when: always
      - when: never

  - local: ${CI_PROJECT_DIR}/ai/.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_REF_PROTECTED != "true" && $CI_PIPELINE_SOURCE != "merge_request_event" && $RUN_INTEGRATION != "true" && $RUN_FULL_TEST != "true"'
        changes:
          - ai/**/*
        when: always 
      - when: never

  - local: ${CI_PROJECT_DIR}/ui/.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_REF_PROTECTED != "true" && $CI_PIPELINE_SOURCE != "merge_request_event" && $RUN_INTEGRATION != "true" && $RUN_FULL_TEST != "true"'
        changes:
          - ui/**/*
        when: always 
      - when: never

  - local: ${CI_PROJECT_DIR}/data/.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_REF_PROTECTED != "true" && $CI_PIPELINE_SOURCE != "merge_request_event" && $RUN_INTEGRATION != "true" && $RUN_FULL_TEST != "true"'
        changes:
          - data/**/*
        when: always 
      - when: never

  - local: ${CI_PROJECT_DIR}/clients/.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_REF_PROTECTED != "true" && $CI_PIPELINE_SOURCE != "merge_request_event" && $RUN_INTEGRATION != "true" && $RUN_FULL_TEST != "true"'
        changes:
          - clients/**/*
        when: always 
      - when: never

  - local: ${CI_PROJECT_DIR}/services/.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_REF_PROTECTED != "true" && $CI_PIPELINE_SOURCE != "merge_request_event" && $RUN_INTEGRATION != "true" && $RUN_FULL_TEST != "true"'
        changes:
          - services/**/*
        when: always
      - when: never


test:downstream:
  stage: build
  trigger:
    include:
      - local: .gitlab/pipelines/test.yml
    strategy: depend
    forward:
      pipeline_variables: true
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
      when: never
    - if: '$RUN_INTEGRATION == "true" || ($CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true")'
      when: always       
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
      when: never
    - if: '$RUN_FULL_TEST == "true" || ($CI_PIPELINE_SOURCE == "merge_request_event") || ($CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH)'
      when: always            
    - when: never

integration:downstream:
  stage: integration
  # needs:    
  #   - job: test:downstream
  #     artifacts: false
  #     optional: true
  trigger:
    include:
      - local: .gitlab/pipelines/integration.yml
    strategy: depend
    forward:
      pipeline_variables: true
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
      when: never
    - if: '$RUN_INTEGRATION == "true" || ($CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true")'
      when: always 
    - when: never    

publish:semantic-release:
  extends: .semantic-release-job
  stage: publish
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "rc"'
      when: manual
    - when: never
  script:
    - export GITLAB_TOKEN=${CI_PUSH_TOKEN}
    - npx semantic-release --ci

release:downstream:
  stage: release
  trigger:
    include:
      - local: .gitlab/pipelines/release.yml
    strategy: depend
    forward:
      pipeline_variables: true
  variables:
    QP_VERSION: $CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
      when: always
    - when: never