import org.gradle.kotlin.dsl.project

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "mill"

include (":core")
include (":core:mill-core")
include (":core:mill-sql")
include (":core:mill-events")
include (":core:mill-events-autoconfigure")
include (":security:mill-security")
include (":core:mill-test-kit")
include (":core:mill-spring-support")

include (":security")
include (":security:mill-security-persistence")
include(":security:mill-security-auth-service")


include (":metadata")
include (":metadata:mill-metadata-core")
include (":metadata:mill-metadata-autoconfigure")
include (":metadata:mill-metadata-service")
include (":metadata:mill-metadata-persistence")

include (":persistence")
include (":persistence:mill-persistence")
include (":persistence:mill-persistence-autoconfigure")
include (":persistence:mill-analysis-persistence")
include (":data")
include (":data:mill-data-backend-core")
include (":data:mill-data-backends")
include (":data:mill-data-testkit")
include (":data:mill-data-autoconfigure")
include (":data:mill-data-source-core")
include (":data:mill-data-source-calcite")
include (":data:mill-data-metadata")
include (":data:mill-data-schema-core")
include (":data:mill-data-schema-service")
include (":data:mill-data-query")
include (":data:mill-data-odata")

include (":data:formats:mill-data-format-text")
include (":data:formats:mill-data-format-excel")
include (":data:formats:mill-data-format-avro")
include (":data:formats:mill-data-format-parquet")
include (":data:formats:mill-data-format-arrow")
include (":data:formats:mill-data-format-json")

include(":security:mill-service-security")
include(":security:mill-security-autoconfigure")

include(":services:mill-service-api")
include(":services:mill-service-common")
include (":services:mill-data-grpc-service")
include (":services:mill-data-http-service")
include (":services:mill-export-service")
include (":services:mill-data-query-service")
include (":services:mill-data-odata-service")
include (":services:mill-analysis-api")
include (":services:mill-analysis-service")
include (":services:mill-ui-service")

include (":ai")
include (":ai:legacy:mill-ai-v1-core")
include (":ai:legacy:mill-ai-v1-nlsql-chat-service")
include (":ai:mill-ai")
include (":ai:mill-ai-data")
include (":ai:mill-ai-test")
include (":ai:mill-ai-cli")
include (":ai:mill-ai-persistence")
include (":ai:mill-ai-autoconfigure")
include (":ai:mill-ai-service")
include (":ai:mill-ai-mcp-core")
include (":ai:mill-ai-mcp-transport-http")

project(":ai:legacy:mill-ai-v1-core").projectDir = file("ai/legacy/mill-ai-v1-core")
project(":ai:legacy:mill-ai-v1-nlsql-chat-service").projectDir = file("ai/legacy/mill-ai-v1-nlsql-chat-service")

include(":cloud")
include(":cloud:aws:mill-cloud-aws-blob")
include(":cloud:aws:mill-cloud-aws-autoconfigure")
include(":cloud:gcp:mill-cloud-gcp-blob")
include(":cloud:gcp:mill-cloud-gcp-autoconfigure")
include(":cloud:azure:mill-cloud-azure-blob")
include(":cloud:azure:mill-cloud-azure-autoconfigure")

include (":clients:mill-jdbc-driver")
include (":clients:mill-jdbc-shell")

include (":apps")
include (":apps:mill-service")

include(":ui")

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven("https://repo.spring.io/milestone")
    }
    versionCatalogs {
        create("libs") {
            from(files("libs.versions.toml"))
        }
    }
}

pluginManagement {
    includeBuild("build-logic")

    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }

    plugins {
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
