/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "mill"

include (":core")
include (":core:mill-core")
include (":core:mill-metadata-core")
include (":core:mill-security-core")
include (":core:mill-service-core")
include (":core:mill-test-kit")

include (":data")
include (":data:mill-data-backends")
include (":data:mill-data-grpc-service")
include (":data:mill-data-http-service")

include (":services")
include (":services:mill-well-known-service")
include (":services:mill-metadata-service")

include (":ui:mill-grinder-service")

include (":ai")
include (":ai:mill-ai-v1-core")
include (":ai:mill-ai-v1-nlsql-chat-service")

include (":ai:mill-ai-v2")
include (":ai:mill-ai-v2-test")

include (":clients:mill-jdbc-driver")
include (":clients:mill-jdbc-shell")

include (":apps")
include (":apps:mill-service")

include (":source")
include (":source:mill-source-core")
include (":source:formats:mill-source-format-text")
include (":source:formats:mill-source-format-excel")
include (":source:formats:mill-source-format-avro")
include (":source:formats:mill-source-format-parquet")
include (":source:mill-source-calcite")


dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        create("libs") {
            from(files("libs.versions.toml"))
        }
    }
}

pluginManagement {
    includeBuild("build-logic")

    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }

    plugins {
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

