mill:
  data:
    sql:
      dialect: CALCITE
    backend:
      type: flow
      flow:
        sources:
          - "src/testIT/resources/flow-skymill-it.yaml"
    services:
      grpc:
        enable: true
        port: 0
        host: "127.0.0.1"
  security:
    enable: false

