services:
  mill-backend:
    image: registry.qpointz.io/qpointz/qpointz/test-integration-backend-mill:feat-jdbc-driver 
    pull_policy: always
    ports:
      - "9099:9099"
    volumes:
      - ./config/ssl/_.local/cert-full.pem:/app/config/ssl/server.crt
      - ./config/ssl/_.local/key.pem:/app/config/ssl/server.key
  mill-backend-auth-tls:
    image: registry.qpointz.io/qpointz/qpointz/test-integration-backend-mill:feat-jdbc-driver 
    pull_policy: always
    ports:
      - "9098:9099"
    environment:
      SPRING_PROFILES_ACTIVE: "auth,tls"
    volumes:
      - ./config/ssl/_.local/cert-full.pem:/app/config/ssl/server.crt
      - ./config/ssl/_.local/key.pem:/app/config/ssl/server.key
  mill-backend-auth:
    image: registry.qpointz.io/qpointz/qpointz/test-integration-backend-mill:feat-jdbc-driver 
    pull_policy: always
    ports:
      - "9097:9099"
    environment:
      SPRING_PROFILES_ACTIVE: "auth"
    volumes:
      - ./config/ssl/_.local/cert-full.pem:/app/config/ssl/server.crt
      - ./config/ssl/_.local/key.pem:/app/config/ssl/server.key
  mill-backend-tls:
    image: registry.qpointz.io/qpointz/qpointz/test-integration-backend-mill:feat-jdbc-driver 
    pull_policy: always
    ports:
      - "9096:9099"
    environment:
      SPRING_PROFILES_ACTIVE: "tls"
    volumes:
      - ./config/ssl/_.local/cert-full.pem:/app/config/ssl/server.crt
      - ./config/ssl/_.local/key.pem:/app/config/ssl/server.key
