qp:
  mill:
    backend:
      calcite:
        connection:
          model: ./config/model.yaml
      security:                        
        enabled: true
        providers:
          - type: file
            path: ./config/passwd.yaml
          - type: jwt
            issuer-uri: "https://login.microsoftonline.com/${AZURE_TEST_TENANT_ID}/discovery/v2.0/keys"

logging:
  level:
    root: info