DROP TABLE IF EXISTS TEST;

create table TEST (
                      id INT NOT NULL,
                      first_name VARCHAR(50),
                      last_name CHAR(50),
                      premium BOOLEAN,
                      age TINYINT,
                      amount SMALLINT,
                      account INT
);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (1, 'Barbee', 'Bonallick', true, 15, 5654, 5016);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (2, 'Aldon', 'Zecchii', false, 2, 3622, 6614);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (3, 'Kennett', 'Prozescky', false, 67, 2810, 9799);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (4, 'Esra', 'Lukash', false, 75, 2019, 816);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (5, 'Enos', 'Spohr', false, 85, 7387, 6381);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (6, 'Melita', 'Iwanowicz', true, 28, 6785, 9326);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (7, 'Candice', 'Roubert', false, 74, 3416, 1920);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (8, 'Iona', 'Corain', true, 6, 1702, 908);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (9, 'Harrison', 'Minogue', true, 78, 170, 3559);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (10, 'Georgeanna', 'Nimmo', true, 21, 1792, 5810);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (11, 'Morris', 'Haslehurst', false, 48, 9040, 5192);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (12, 'Milicent', 'Cammack', true, 17, 4637, 6807);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (13, 'Cara', 'Malt', true, 88, 386, 1099);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (14, 'Lorain', 'Creasey', false, 28, 2666, 2304);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (15, 'Adrianna', 'Piwell', false, 10, 75, 2507);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (16, 'Galen', 'Extal', false, 39, 1168, 3853);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (17, 'Lemuel', 'Ericsson', false, 73, 6623, 6291);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (18, 'Byran', 'Benaine', true, 64, 7816, 4165);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (19, 'Jeanine', 'McPolin', true, 30, 2342, 2015);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (20, 'Zaria', 'Pellant', true, 78, 7893, 1281);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (21, 'Larisa', 'McGifford', false, 73, 8528, 3757);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (22, 'Althea', 'Stickney', true, 53, 2912, 1942);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (23, 'Web', 'Brazil', false, 85, 2730, 1396);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (24, 'Kylila', 'Arnli', true, 52, 6980, 6440);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (25, 'Frederique', 'Keijser', true, 74, 6892, 3774);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (26, 'Abner', 'Childe', false, 78, 8979, 405);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (27, 'Robinson', 'Gait', false, 58, 9494, 3302);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (28, 'Garret', 'Baudoux', false, 30, 8333, 6298);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (29, 'Humfrey', 'Linster', false, 77, 9131, 9226);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (30, 'Morris', 'Pistol', true, 102, 7728, 3912);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (31, 'Shaw', 'Momery', true, 24, 6594, 9183);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (32, 'Northrup', 'Maxwale', true, 15, 216, 4628);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (33, 'Zena', 'Steinor', true, 55, 4132, 3746);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (34, 'Dorey', 'Jedrzejewicz', true, 6, 3581, 3139);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (35, 'Harley', 'Seccombe', false, 87, 9978, 6888);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (36, 'Audrye', 'Di Pietro', true, 13, 8970, 4248);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (37, 'Brien', 'Forestall', false, 102, 8548, 7146);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (38, 'Zaccaria', 'Mostin', false, 43, 1147, 5540);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (39, 'Josepha', 'Bruhnicke', false, 26, 7639, 4695);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (40, 'Shandee', 'Guage', false, 3, 6995, 678);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (41, 'Bronny', 'Plampeyn', false, 13, 5141, 9345);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (42, 'Brodie', 'Paterno', false, 27, 3482, 8966);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (43, 'Philip', 'Boughton', false, 42, 575, 7841);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (44, 'Julie', 'Stirtle', true, 16, 643, 674);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (45, 'Dominga', 'Hands', true, 56, 4843, 8420);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (46, 'Leshia', 'Becke', false, 62, 3545, 5082);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (47, 'Clint', 'Lynock', false, 16, 7318, 6186);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (48, 'Sam', 'Klosterman', true, 23, 4941, 1551);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (49, 'Ursulina', 'Bunford', false, 6, 6658, 3632);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (50, 'Nara', 'Giral', true, 83, 5074, 4480);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (51, 'Hodge', 'Basden', false, 76, 5972, 5150);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (52, 'Vern', 'Cerith', false, 108, 8517, 778);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (53, 'Emery', 'Blackway', true, 33, 2851, 826);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (54, 'Kerry', 'Dubock', true, 85, 1493, 5881);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (55, 'Daffi', 'Kerwen', false, 55, 3122, 1074);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (56, 'Brand', 'Eusden', true, 70, 8942, 7527);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (57, 'Daniela', 'Earley', true, 54, 3123, 4349);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (58, 'Alie', 'Wiffill', true, 86, 1950, 2733);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (59, 'Felipa', 'Newtown', true, 24, 9826, 1463);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (60, 'Catherin', 'Vanderplas', true, 9, 6847, 5291);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (61, 'Hort', 'Radloff', true, 23, 3201, 5597);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (62, 'Kori', 'Dyos', false, 13, 1562, 3152);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (63, 'Upton', 'Jado', true, 10, 1004, 9120);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (64, 'Viki', 'Engeham', true, 100, 7216, 4472);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (65, 'Danell', 'Reside', true, 85, 747, 5128);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (66, 'Leah', 'Gatherer', false, 103, 4407, 877);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (67, 'Mariann', 'Schwandermann', false, 30, 353, 5876);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (68, 'Konstanze', 'Cabera', false, 80, 1270, 6029);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (69, 'Ruby', 'O''Dempsey', false, 84, 9815, 5577);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (70, 'Carol-jean', 'Pashley', true, 110, 2578, 9625);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (71, 'Cathryn', 'Tuther', false, 15, 6359, 586);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (72, 'Byrle', 'Leatherland', true, 102, 3017, 7010);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (73, 'Mollee', 'McAlees', true, 22, 7237, 3877);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (74, 'Abe', 'Paulino', false, 110, 1724, 6690);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (75, 'Albertina', 'Dunckley', false, 108, 1297, 9642);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (76, 'Robby', 'Sheirlaw', false, 110, 1713, 6725);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (77, 'Judi', 'Medlicott', false, 81, 3078, 9823);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (78, 'Celinka', 'Gerald', true, 45, 7350, 8775);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (79, 'Dunstan', 'Kleinbaum', true, 85, 7334, 3963);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (80, 'Annelise', 'Iacopini', false, 3, 864, 6083);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (81, 'Dermot', 'Lamswood', false, 78, 813, 3321);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (82, 'Abbi', 'Fitchell', true, 43, 9330, 6327);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (83, 'Hughie', 'Bendan', true, 16, 9440, 3496);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (84, 'Gradey', 'O''Lenane', true, 22, 8836, 3427);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (85, 'Gabby', 'Harlick', true, 24, 4853, 3822);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (86, 'Kylen', 'Ashwell', false, 71, 4216, 6532);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (87, 'Dex', 'Breeton', true, 43, 7892, 4336);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (88, 'Farlie', 'Corkell', false, 80, 9220, 3013);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (89, 'Twila', 'Engel', false, 78, 3974, 917);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (90, 'Orson', 'Wheble', true, 102, 5777, 2193);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (91, 'Stephie', 'Chalfont', false, 63, 3439, 8678);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (92, 'Charles', 'Pracy', true, 101, 7842, 657);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (93, 'Mil', 'Etock', false, 102, 2152, 9085);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (94, 'Emlyn', 'Greep', true, 41, 8168, 678);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (95, 'Prescott', 'Bridel', true, 43, 5825, 1846);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (96, 'Charlene', 'Beiderbeck', true, 58, 1768, 5264);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (97, 'Kim', 'Knoble', false, 50, 4063, 882);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (98, 'Nadine', 'Overshott', false, 20, 1158, 9578);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (99, 'Avie', 'Rasper', false, 53, 3643, 7736);
insert into TEST (id, first_name, last_name, premium, age, amount, account) values (100, 'Florence', 'Pakeman', true, 18, 325, 9221);

SELECT * from TEST;