# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import data_connect_svc_pb2 as data__connect__svc__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in data_connect_svc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataConnectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/io.qpointz.mill.DataConnectService/Handshake',
                request_serializer=data__connect__svc__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=data__connect__svc__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.ListSchemas = channel.unary_unary(
                '/io.qpointz.mill.DataConnectService/ListSchemas',
                request_serializer=data__connect__svc__pb2.ListSchemasRequest.SerializeToString,
                response_deserializer=data__connect__svc__pb2.ListSchemasResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/io.qpointz.mill.DataConnectService/GetSchema',
                request_serializer=data__connect__svc__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=data__connect__svc__pb2.GetSchemaResponse.FromString,
                _registered_method=True)
        self.ParseSql = channel.unary_unary(
                '/io.qpointz.mill.DataConnectService/ParseSql',
                request_serializer=data__connect__svc__pb2.ParseSqlRequest.SerializeToString,
                response_deserializer=data__connect__svc__pb2.ParseSqlResponse.FromString,
                _registered_method=True)
        self.ExecQuery = channel.unary_stream(
                '/io.qpointz.mill.DataConnectService/ExecQuery',
                request_serializer=data__connect__svc__pb2.QueryRequest.SerializeToString,
                response_deserializer=data__connect__svc__pb2.QueryResultResponse.FromString,
                _registered_method=True)
        self.SubmitQuery = channel.unary_unary(
                '/io.qpointz.mill.DataConnectService/SubmitQuery',
                request_serializer=data__connect__svc__pb2.QueryRequest.SerializeToString,
                response_deserializer=data__connect__svc__pb2.QueryResultResponse.FromString,
                _registered_method=True)
        self.FetchQueryResult = channel.unary_unary(
                '/io.qpointz.mill.DataConnectService/FetchQueryResult',
                request_serializer=data__connect__svc__pb2.QueryResultRequest.SerializeToString,
                response_deserializer=data__connect__svc__pb2.QueryResultResponse.FromString,
                _registered_method=True)


class DataConnectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchemas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseSql(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchQueryResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataConnectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=data__connect__svc__pb2.HandshakeRequest.FromString,
                    response_serializer=data__connect__svc__pb2.HandshakeResponse.SerializeToString,
            ),
            'ListSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchemas,
                    request_deserializer=data__connect__svc__pb2.ListSchemasRequest.FromString,
                    response_serializer=data__connect__svc__pb2.ListSchemasResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=data__connect__svc__pb2.GetSchemaRequest.FromString,
                    response_serializer=data__connect__svc__pb2.GetSchemaResponse.SerializeToString,
            ),
            'ParseSql': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseSql,
                    request_deserializer=data__connect__svc__pb2.ParseSqlRequest.FromString,
                    response_serializer=data__connect__svc__pb2.ParseSqlResponse.SerializeToString,
            ),
            'ExecQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecQuery,
                    request_deserializer=data__connect__svc__pb2.QueryRequest.FromString,
                    response_serializer=data__connect__svc__pb2.QueryResultResponse.SerializeToString,
            ),
            'SubmitQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitQuery,
                    request_deserializer=data__connect__svc__pb2.QueryRequest.FromString,
                    response_serializer=data__connect__svc__pb2.QueryResultResponse.SerializeToString,
            ),
            'FetchQueryResult': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchQueryResult,
                    request_deserializer=data__connect__svc__pb2.QueryResultRequest.FromString,
                    response_serializer=data__connect__svc__pb2.QueryResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'io.qpointz.mill.DataConnectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('io.qpointz.mill.DataConnectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataConnectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.qpointz.mill.DataConnectService/Handshake',
            data__connect__svc__pb2.HandshakeRequest.SerializeToString,
            data__connect__svc__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.qpointz.mill.DataConnectService/ListSchemas',
            data__connect__svc__pb2.ListSchemasRequest.SerializeToString,
            data__connect__svc__pb2.ListSchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.qpointz.mill.DataConnectService/GetSchema',
            data__connect__svc__pb2.GetSchemaRequest.SerializeToString,
            data__connect__svc__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseSql(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.qpointz.mill.DataConnectService/ParseSql',
            data__connect__svc__pb2.ParseSqlRequest.SerializeToString,
            data__connect__svc__pb2.ParseSqlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/io.qpointz.mill.DataConnectService/ExecQuery',
            data__connect__svc__pb2.QueryRequest.SerializeToString,
            data__connect__svc__pb2.QueryResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.qpointz.mill.DataConnectService/SubmitQuery',
            data__connect__svc__pb2.QueryRequest.SerializeToString,
            data__connect__svc__pb2.QueryResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchQueryResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.qpointz.mill.DataConnectService/FetchQueryResult',
            data__connect__svc__pb2.QueryResultRequest.SerializeToString,
            data__connect__svc__pb2.QueryResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
