# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statement.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'statement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .substrait import plan_pb2 as substrait_dot_plan__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstatement.proto\x12\x0fio.qpointz.mill\x1a\x14substrait/plan.proto\x1a\x0c\x63ommon.proto\"\xf0\x01\n\tParameter\x12\r\n\x05index\x18\x01 \x01(\r\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\'\n\x04type\x18\x03 \x01(\x0b\x32\x19.io.qpointz.mill.DataType\x12\x16\n\x0c\x62ooleanValue\x18\n \x01(\x08H\x00\x12\x15\n\x0bstringValue\x18\x0b \x01(\tH\x00\x12\x14\n\nint32Value\x18\x0c \x01(\x05H\x00\x12\x14\n\nint64Value\x18\r \x01(\x03H\x00\x12\x14\n\nfloatValue\x18\x0e \x01(\x02H\x00\x12\x15\n\x0b\x64oubleValue\x18\x0f \x01(\x01H\x00\x42\x07\n\x05valueB\x07\n\x05_name\"K\n\x0cSQLStatement\x12\x0b\n\x03sql\x18\x01 \x01(\t\x12.\n\nparameters\x18\x02 \x03(\x0b\x32\x1a.io.qpointz.mill.Parameter\".\n\rPlanStatement\x12\x1d\n\x04plan\x18\x01 \x01(\x0b\x32\x0f.substrait.Plan\"\x8a\x01\n\x11TextPlanStatement\x12\x0c\n\x04plan\x18\x01 \x01(\t\x12\x41\n\x06\x66ormat\x18\x02 \x01(\x0e\x32\x31.io.qpointz.mill.TextPlanStatement.TextPlanFormat\"$\n\x0eTextPlanFormat\x12\x08\n\x04JSON\x10\x00\x12\x08\n\x04YAML\x10\x01\x42\x19\n\x15io.qpointz.mill.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025io.qpointz.mill.protoP\001'
  _globals['_PARAMETER']._serialized_start=73
  _globals['_PARAMETER']._serialized_end=313
  _globals['_SQLSTATEMENT']._serialized_start=315
  _globals['_SQLSTATEMENT']._serialized_end=390
  _globals['_PLANSTATEMENT']._serialized_start=392
  _globals['_PLANSTATEMENT']._serialized_end=438
  _globals['_TEXTPLANSTATEMENT']._serialized_start=441
  _globals['_TEXTPLANSTATEMENT']._serialized_end=579
  _globals['_TEXTPLANSTATEMENT_TEXTPLANFORMAT']._serialized_start=543
  _globals['_TEXTPLANSTATEMENT_TEXTPLANFORMAT']._serialized_end=579
# @@protoc_insertion_point(module_scope)
