# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'vector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvector.proto\x12\x0fio.qpointz.mill\x1a\x0c\x63ommon.proto\";\n\x11VectorBlockSchema\x12&\n\x06\x66ields\x18\x03 \x03(\x0b\x32\x16.io.qpointz.mill.Field\"\x7f\n\x0bVectorBlock\x12\x32\n\x06schema\x18\x01 \x01(\x0b\x32\".io.qpointz.mill.VectorBlockSchema\x12\x12\n\nvectorSize\x18\x02 \x01(\r\x12(\n\x07vectors\x18\x03 \x03(\x0b\x32\x17.io.qpointz.mill.Vector\"\xe0\x05\n\x06Vector\x12\x10\n\x08\x66ieldIdx\x18\x01 \x01(\r\x12\x32\n\x05nulls\x18\x02 \x01(\x0b\x32#.io.qpointz.mill.Vector.NullsVector\x12<\n\x0cstringVector\x18\x64 \x01(\x0b\x32$.io.qpointz.mill.Vector.StringVectorH\x00\x12\x36\n\ti32Vector\x18\x65 \x01(\x0b\x32!.io.qpointz.mill.Vector.I32VectorH\x00\x12\x36\n\ti64Vector\x18\x66 \x01(\x0b\x32!.io.qpointz.mill.Vector.I64VectorH\x00\x12\x38\n\nfp64Vector\x18g \x01(\x0b\x32\".io.qpointz.mill.Vector.FP64VectorH\x00\x12\x38\n\nfp32Vector\x18h \x01(\x0b\x32\".io.qpointz.mill.Vector.FP32VectorH\x00\x12\x38\n\nboolVector\x18i \x01(\x0b\x32\".io.qpointz.mill.Vector.BoolVectorH\x00\x12\x39\n\nbyteVector\x18j \x01(\x0b\x32#.io.qpointz.mill.Vector.BytesVectorH\x00\x1a\x1c\n\x0bNullsVector\x12\r\n\x05nulls\x18\x02 \x03(\x08\x1a\x1e\n\x0cStringVector\x12\x0e\n\x06values\x18\x01 \x03(\t\x1a\x1b\n\tI32Vector\x12\x0e\n\x06values\x18\x01 \x03(\x05\x1a\x1b\n\tI64Vector\x12\x0e\n\x06values\x18\x01 \x03(\x03\x1a\x1c\n\nFP64Vector\x12\x0e\n\x06values\x18\x01 \x03(\x01\x1a\x1c\n\nFP32Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\x1a\x1c\n\nBoolVector\x12\x0e\n\x06values\x18\x01 \x03(\x08\x1a\x1d\n\x0b\x42ytesVector\x12\x0e\n\x06values\x18\x01 \x03(\x0c\x42\x08\n\x06valuesB\x1f\n\x15io.qpointz.mill.protoP\x01\x88\x01\x01\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025io.qpointz.mill.protoP\001\210\001\001\220\001\001'
  _globals['_VECTORBLOCKSCHEMA']._serialized_start=47
  _globals['_VECTORBLOCKSCHEMA']._serialized_end=106
  _globals['_VECTORBLOCK']._serialized_start=108
  _globals['_VECTORBLOCK']._serialized_end=235
  _globals['_VECTOR']._serialized_start=238
  _globals['_VECTOR']._serialized_end=974
  _globals['_VECTOR_NULLSVECTOR']._serialized_start=725
  _globals['_VECTOR_NULLSVECTOR']._serialized_end=753
  _globals['_VECTOR_STRINGVECTOR']._serialized_start=755
  _globals['_VECTOR_STRINGVECTOR']._serialized_end=785
  _globals['_VECTOR_I32VECTOR']._serialized_start=787
  _globals['_VECTOR_I32VECTOR']._serialized_end=814
  _globals['_VECTOR_I64VECTOR']._serialized_start=816
  _globals['_VECTOR_I64VECTOR']._serialized_end=843
  _globals['_VECTOR_FP64VECTOR']._serialized_start=845
  _globals['_VECTOR_FP64VECTOR']._serialized_end=873
  _globals['_VECTOR_FP32VECTOR']._serialized_start=875
  _globals['_VECTOR_FP32VECTOR']._serialized_end=903
  _globals['_VECTOR_BOOLVECTOR']._serialized_start=905
  _globals['_VECTOR_BOOLVECTOR']._serialized_end=933
  _globals['_VECTOR_BYTESVECTOR']._serialized_start=935
  _globals['_VECTOR_BYTESVECTOR']._serialized_end=964
# @@protoc_insertion_point(module_scope)
