include:
  - local : /.gitlab/vars.yml
  - local : /.gitlab/jobs.yml

workflow:
  rules:
    - when : always

image: $CI_IMAGE_SBT
stages:
  - init
  - test
  - integration
  - report
  - package
  - deploy

cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - project/
    - ./**/target/
    - target/
    - project/project

flow:test:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}/flow
    - sbt clean coverage test coverageReport coverageAggregate
    - cd target/scala-2.13
    - tar -czvf ./scoverage-report.tar.gz ./scoverage-report
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/flow/target/scala-2.13/scoverage-report.tar.gz
    reports:
      junit: ${CI_PROJECT_DIR}/flow/**/*/target/test-reports/*.xml

# doc:html:
#   stage: test
#   script:
#     - cd ${CI_PROJECT_DIR}/flow
#     - cd docs && make html && cd build && tar -czvf ./docs-html.tar.gz ./html
#   artifacts:
#     name: "doc-html-$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG"
#     paths:
#       - ./docs/build/docs-html.tar.gz

#publishToMaven:
#  stage: package
#  only:
#    - dev
#    - master
#  script:
#    - cd ${CI_PROJECT_DIR}/flow
#    - sbt clean publish

# scalastyle:
#   stage: report
#   script:
#     - cd ${CI_PROJECT_DIR}/flow
#     - sbt scalastyle
#     - etc/misc/checkstyle.sh
#   artifacts:
#     untracked: true
#     paths:
#       - target/scalastyle/*.*
#     expire_in: 10 days

# publishDocAndReports:
#   image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#   stage: deploy
#   script:
#     - aws s3 rm --recursive s3://qpointz-cicd/$CI_COMMIT_REF_SLUG
#     - mkdir pub
#     - mkdir pub/docs && tar -xzf ./docs/build/docs-html.tar.gz  -C ./pub/docs --strip-components=2
#     - cp -R ./target/scalastyle/ ./pub/scalastyle
#     - mkdir pub/coverage && tar -xzvf ./target/scala-2.13/scoverage-report.tar.gz -C ./pub/coverage --strip-components=2
#     - aws s3 cp --recursive pub s3://qpointz-cicd/$CI_COMMIT_REF_SLUG
#     - rm -Rf ./pub