rapids:
  calcite:
    mode: standard
    standard:
      properties:
        model : ./etc/model.json
        quoting : DOUBLE_QUOTE
        caseSensitive : true
#  security:
#    identity:
#      provider: basic
#      basic:
#        config: ./config/passwd
#    auth:
#      provider: simple
#      simple:
#        allow-roles:
#          - reader
#          - grinder
  services:
    jdbc:
      enabled : true
      port : 18200
      protocol: json
    odata:
      enabled : true
      port : 18080
      namespace : "io.qpointz.test"