grpc:
  server:
    security:
      enabled: false
qp:
  mill:
    backend:
      calcite:
        connection:
          model: ./config/model.yaml
      security:
        enabled: false

logging:
  level:
    root: info