spring:
  profiles:
    include:
      - 'backend'
  application:
    name: mill-calcite-backend
qp:
  mill:
    backend:
      calcite:
        connection:
          quoting: BACK_TICK
          caseSensitive: true
          unquotedCasing: UNCHANGED