DROP TABLE IF EXISTS DTYPES ;

CREATE TABLE DTYPES (
      ID BIGINT AUTO_INCREMENT
    , TEST CHARACTER(10)

    , STR CHARACTER(20) NULL
    , STR_VAR CHARACTER VARYING(150) NULL
    , BOOL BOOLEAN NULL
    , INT32F INT NULL
    , INT64F BIGINT NULL
    , DOUBLEF DOUBLE PRECISION NULL
    , FLOATF REAL NULL

    , BIN_FIX BINARY(10) NULL
    , BIN_VAR BINARY VARYING(100) NULL
    , DATEF DATE NULL
    , TIME_NO_TZ TIME WITHOUT TIME ZONE NULL
    , TS_NO_TZ   TIMESTAMP WITHOUT TIME ZONE NULL
);

INSERT INTO DTYPES(TEST, STR, STR_VAR) VALUES ('STRING', 'FIXED', 'VARIABLE_STRING');
INSERT INTO DTYPES(TEST, STR, STR_VAR) VALUES ('STRING', NULL, NULL);

INSERT INTO DTYPES(TEST, BOOL) VALUES ('BOOL', NULL);
INSERT INTO DTYPES(TEST, BOOL) VALUES ('BOOL', FALSE);
INSERT INTO DTYPES(TEST, BOOL) VALUES ('BOOL', TRUE);

INSERT INTO DTYPES(TEST, INT32F) VALUES ('INT32', NULL);
INSERT INTO DTYPES(TEST, INT32F) VALUES ('INT32', 234);

INSERT INTO DTYPES(TEST, INT64F) VALUES ('INT64', NULL);
INSERT INTO DTYPES(TEST, INT64F) VALUES ('INT64', 1234);

INSERT INTO DTYPES(TEST, DOUBLEF) VALUES('DOUBLE', NULL);
INSERT INTO DTYPES(TEST, DOUBLEF) VALUES('DOUBLE', -1.234);

INSERT INTO DTYPES(TEST, FLOATF) VALUES('FLOAT', NULL);
INSERT INTO DTYPES(TEST, FLOATF) VALUES('FLOAT', 567890.3824);

INSERT INTO DTYPES(TEST, BIN_FIX) VALUES('BIN_FIX', NULL);
INSERT INTO DTYPES(TEST, BIN_FIX) VALUES('BIN_FIX', X'01 FF FA CD 03 2D D3');

INSERT INTO DTYPES(TEST, BIN_VAR) VALUES('BIN_VAR', NULL);
INSERT INTO DTYPES(TEST, BIN_VAR) VALUES('BIN_VAR', X'07 A2 FE 92 65 FF E4');

INSERT INTO DTYPES(TEST, DATEF) VALUES('DATE', null);
INSERT INTO DTYPES(TEST, DATEF) VALUES('DATE', '2013-12-31');


INSERT INTO DTYPES(TEST, TIME_NO_TZ, TS_NO_TZ ) VALUES('TIME', NULL, NULL);
INSERT INTO DTYPES(TEST, TIME_NO_TZ, TS_NO_TZ ) VALUES('TIME', '10:12:00',  '2014-07-25 11:15:16');
INSERT INTO DTYPES(TEST, TIME_NO_TZ, TS_NO_TZ ) VALUES('TIME', '10:33:05.123', '1976-10-07 19:18:33.125');

/*
SELECT * FROM DTYPES;
 */