clients:mill-py:test:
  extends: .python-mill-py-unit-test
  variables:
    TEST_TYPE: "unit"
    PY_VER: "${DEFAULT_PY_VER}"

clients:mill-jdbc-driver:build:
  stage: build
  extends: .gradle-job
  script:
    - ./gradlew --no-daemon ${GRADLE_CONTINUE_PARAM} --console plain :clients:test :clients:compileTestIT
  artifacts:
    when: always
    expire_in: "5 days"
    paths:
      - ${CI_PROJECT_DIR}/clients/mill-jdbc-driver/build/reports/tests/test/
      - ${CI_PROJECT_DIR}/clients/mill-jdbc-driver/build/reports/jacoco/test/
    reports:
      junit:
        - ${CI_PROJECT_DIR}/clients/mill-jdbc-driver/build/test-results/test/TEST-*.xml