include:
  - local : /.gitlab/vars.yml
  - local : /.gitlab/jobs.yml

image: ${CI_IMAGE_GRADLE}

stages:
  - init  
  - test

workflow:
  rules:
    - when : always

mill-clients:init-version:
  stage: init
  extends: .init-next-version  

mill:init-certs:
  stage: init
  image: "${CI_IMAGE_MINICA}"
  script:         
    - cp -R /certs ${CI_PROJECT_DIR}/etc    
    - cp ${CI_PROJECT_DIR}/etc/certs/_\.local/cert.pem ${CI_PROJECT_DIR}/mill-clients/mill-py/etc/mill-test-service/server.crt
    - cp ${CI_PROJECT_DIR}/etc/certs/_\.local/key.pem ${CI_PROJECT_DIR}/mill-clients/mill-py/etc/mill-test-service/server.key
  artifacts:    
    when: always
    expire_in: "1 days"
    paths:
      - ${CI_PROJECT_DIR}/etc/certs/**/*
      - ${CI_PROJECT_DIR}/mill-clients/mill-py/etc/mill-test-service/server.*

init:build-test-backend-service:
  stage: init
  extends: .docker-build-job
  script:
      - >
        /kaniko/executor
        --build-arg AZ_TID=$AZ_TEST_TENANT_ID
        --build-arg BASE_IMAGE=${CI_REGISTRY_IMAGE}/mill-calcite-backend:${CI_COMMIT_REF_SLUG} 
        --context "${CI_PROJECT_DIR}/mill-clients/mill-py/etc/mill-test-service" 
        --destination "${CI_REGISTRY_IMAGE}/test-backend-mill-py:${CI_COMMIT_REF_SLUG}"                
        --cache=true      
  needs:
    - job: mill-clients:init-version
      artifacts: true
    - job: mill:init-certs
      artifacts: true

mill:init-az-login:
  stage: init
  image: mcr.microsoft.com/azure-cli:cbl-mariner2.0  
  script:
    - az config set core.only_show_errors=yes
    - az login --service-principal -u ${AZ_TEST_SPN} --password ${AZ_TEST_SPN_SECRET} --tenant ${AZ_TEST_TENANT_ID} --allow-no-subscription
    - AZ_TOKEN=$(az account get-access-token --scope ${AZ_TEST_SCOPE}/.default --query "accessToken" --output tsv)
    - echo -n $AZ_TOKEN > ${CI_PROJECT_DIR}/etc/.test_az_token    
  artifacts:    
    expire_in: "1 days"
    paths:
      - ${CI_PROJECT_DIR}/etc/.test_az_token

.mill-client:python:test:  
  stage: test
  services:
    - name: ${CI_REGISTRY_IMAGE}/test-backend-mill-py:${CI_COMMIT_REF_SLUG}
      pull_policy: always
      variables:
        SPRING_PROFILES_ACTIVE: "jwt,tls"        
      alias: backend-secure.local
      entrypoint:
        - "./bin/calcite-backend-service"        
      command:
        - ""
  variables:
    CI_DEBUG_SERVICES: "true"    
    MILL_HOST_SECURE: backend-secure.local
    MILL_CA_FILE: ${CI_PROJECT_DIR}/etc/certs/ca.pem    
    MILL_PORT_SECURE: "9099"
  before_script:    
    - !reference [.global-vars, before_script]
    - cd ${CI_PROJECT_DIR}/mill-clients/mill-py
    - pip install -r requirements.txt    
  script:    
    - cd ${CI_PROJECT_DIR}/mill-clients/mill-py
    - export AZ_TEST_TOKEN="$(cat ${CI_PROJECT_DIR}/etc/.test_az_token)"    
    - python -m unittest discover -s ./tests
  needs: 
    - job: mill:init-certs
      artifacts: true
    - job: mill-clients:init-version
      artifacts: true
    - job: mill:init-az-login
      artifacts: true
    - job: init:build-test-backend-service
      artifacts: false

mill-client:python:test-3.10:
  extends: .mill-client:python:test
  image: python:3.10-slim  

mill-client:python:test-3.11:
  extends: .mill-client:python:test
  image: python:3.11-slim   

mill-client:python:test-3.12:
  extends: .mill-client:python:test
  image: python:3.12-slim