version: 1.0
defaultSchema: airlines
schemas:
  - name: airlines
    type: custom
    factory: org.apache.calcite.adapter.csv.CsvSchemaFactory
    operand:
      directory: ./airlines
  - name: ts
    type: jdbc
    jdbcDriver: "org.h2.Driver"
    jdbcUrl: "jdbc:h2:mem:test;INIT=RUNSCRIPT FROM './etc/sample/users/users.sql'"