package io.qpointz.mill.persistence.metadata.jpa.entities

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Index
import jakarta.persistence.Lob
import jakarta.persistence.Table
import java.time.Instant

/**
 * JPA entity representing an immutable audit log entry in `metadata_operation_audit`.
 *
 * Written by [io.qpointz.mill.persistence.metadata.jpa.adapters.JpaMetadataChangeObserver] for
 * every [io.qpointz.mill.metadata.domain.MetadataChangeEvent] received. Rows are never updated
 * or deleted; the table is append-only.
 *
 * The [payloadBefore] and [payloadAfter] LOBs hold JSON-serialised entity or facet payloads for
 * `EntityUpdated` and `FacetUpdated` events. They are `null` for events where only one side
 * exists (e.g. `EntityCreated` has no `payloadBefore`).
 *
 * @property auditId       stable identifier; UUID generated by the observer
 * @property operationType event type name (e.g. `EntityCreated`, `FacetUpdated`, `Imported`)
 * @property entityId      identifier of the affected entity; may be `null` for type-level events
 * @property facetType     full Mill facet-type URN; present only for facet-level events
 * @property scopeKey      full Mill scope URN; present only for facet-level events
 * @property actorId       identifier of the actor who triggered the change
 * @property occurredAt    timestamp of the originating change event
 * @property payloadBefore JSON-serialised pre-change payload; `null` when not applicable
 * @property payloadAfter  JSON-serialised post-change payload; `null` when not applicable
 * @property changeSummary short human-readable description of the change; optional
 */
@Entity
@Table(
    name = "metadata_operation_audit",
    indexes = [
        Index(name = "idx_moa_entity",    columnList = "entity_id"),
        Index(name = "idx_moa_actor",     columnList = "actor_id"),
        Index(name = "idx_moa_occurred",  columnList = "occurred_at"),
        Index(name = "idx_moa_operation", columnList = "operation_type")
    ]
)
class MetadataOperationAuditEntity(

    @Id
    @Column(name = "audit_id", nullable = false, length = 255)
    val auditId: String,

    @Column(name = "operation_type", nullable = false, length = 32)
    val operationType: String,

    @Column(name = "entity_id", length = 255)
    val entityId: String?,

    @Column(name = "facet_type", length = 255)
    val facetType: String?,

    @Column(name = "scope_key", length = 512)
    val scopeKey: String?,

    @Column(name = "actor_id", nullable = false, length = 255)
    val actorId: String,

    @Column(name = "occurred_at", nullable = false)
    val occurredAt: Instant,

    @Lob
    @Column(name = "payload_before", columnDefinition = "CLOB")
    val payloadBefore: String?,

    @Lob
    @Column(name = "payload_after", columnDefinition = "CLOB")
    val payloadAfter: String?,

    @Column(name = "change_summary", length = 1024)
    val changeSummary: String?
)
