package io.qpointz.mill.persistence.metadata.jpa.entities

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Index
import jakarta.persistence.Table
import java.time.Instant

/**
 * JPA entity representing an immutable audit log entry in `metadata_operation_audit`.
 *
 * @property auditId        Stable identifier; UUID generated by the observer
 * @property operationType  Event type name (e.g. `EntityCreated`, `FacetUpdated`, `Imported`)
 * @property entityId       Optional surrogate id when resolvable; may be `null`
 * @property entityRes      Business entity FQDN snapshot; may be `null` for type-level events
 * @property facetTypeRes   Full Mill facet-type URN; present only for facet-level events
 * @property scopeRes       Full Mill scope URN; present only for facet-level events
 * @property actorId        Identifier of the actor who triggered the change
 * @property occurredAt     Timestamp of the originating change event
 * @property payloadBefore  JSON-serialised pre-change payload; `null` when not applicable
 * @property payloadAfter   JSON-serialised post-change payload; `null` when not applicable
 * @property changeSummary  Short human-readable description of the change; optional
 */
@Entity
@Table(
    name = "metadata_operation_audit",
    indexes = [
        Index(name = "idx_moa_entity", columnList = "entity_id"),
        Index(name = "idx_moa_actor", columnList = "actor_id"),
        Index(name = "idx_moa_occurred", columnList = "occurred_at"),
        Index(name = "idx_moa_operation", columnList = "operation_type")
    ]
)
class MetadataOperationAuditEntity(

    @Id
    @Column(name = "audit_id", nullable = false, length = 255)
    val auditId: String,

    @Column(name = "operation_type", nullable = false, length = 32)
    val operationType: String,

    @Column(name = "entity_id")
    val entityId: Long?,

    @Column(name = "entity_res", length = 255)
    val entityRes: String?,

    @Column(name = "facet_type_res", length = 255)
    val facetTypeRes: String?,

    @Column(name = "scope_res", length = 512)
    val scopeRes: String?,

    @Column(name = "actor_id", nullable = false, length = 255)
    val actorId: String,

    @Column(name = "occurred_at", nullable = false)
    val occurredAt: Instant,

    @Column(name = "payload_before", columnDefinition = "TEXT")
    val payloadBefore: String?,

    @Column(name = "payload_after", columnDefinition = "TEXT")
    val payloadAfter: String?,

    @Column(name = "change_summary", length = 1024)
    val changeSummary: String?
)
