package io.qpointz.mill.persistence.metadata.jpa.entities

import jakarta.persistence.Column
import jakarta.persistence.ConstraintMode
import jakarta.persistence.Entity
import jakarta.persistence.ForeignKey
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Index
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Table
import jakarta.persistence.UniqueConstraint
import java.time.Instant

/**
 * JPA entity representing a single facet payload stored under a specific scope in
 * `metadata_facet_scope`.
 *
 * Each row holds the JSON-serialised payload for one (entity, facet-type, scope) triple.
 * The combination `(entity_id, facet_type, scope_id)` is guaranteed unique by a database
 * constraint.
 *
 * @property facetScopeId surrogate primary key; auto-generated by the database
 * @property entityId     foreign key to [MetadataEntityRecord]; owning entity identifier
 * @property facetType    full Mill facet-type URN (e.g. `urn:mill/metadata/facet-type:descriptive`)
 * @property scope        the [MetadataScopeEntity] this payload is stored under
 * @property payloadJson  JSON-serialised facet payload as a text column; defaults to `{}`
 * @property createdAt    creation timestamp
 * @property updatedAt    last-modified timestamp
 * @property createdBy    actor who created this row
 * @property updatedBy    actor who last modified this row
 */
@Entity
@Table(
    name = "metadata_facet_scope",
    indexes = [
        Index(name = "idx_mfs_entity", columnList = "entity_id"),
        Index(name = "idx_mfs_facet",  columnList = "facet_type"),
        Index(name = "idx_mfs_scope",  columnList = "scope_id")
    ],
    uniqueConstraints = [
        UniqueConstraint(name = "uq_metadata_facet_scope", columnNames = ["entity_id", "facet_type", "scope_id"])
    ]
)
class MetadataFacetScopeEntity(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "facet_scope_id", nullable = false)
    val facetScopeId: Long = 0,

    @Column(name = "entity_id", nullable = false, length = 255)
    var entityId: String,

    @Column(name = "facet_type", nullable = false, length = 255)
    var facetType: String,

    @ManyToOne(optional = false)
    @JoinColumn(
        name = "scope_id",
        nullable = false,
        foreignKey = ForeignKey(ConstraintMode.CONSTRAINT)
    )
    var scope: MetadataScopeEntity,

    @Column(name = "payload_json", nullable = false, columnDefinition = "TEXT")
    var payloadJson: String = "{}",

    @Column(name = "created_at", nullable = false)
    val createdAt: Instant,

    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,

    @Column(name = "created_by", length = 255)
    var createdBy: String?,

    @Column(name = "updated_by", length = 255)
    var updatedBy: String?
)
