"""Mill schema explorer platform HTTP client."""
from __future__ import annotations

from mill.schema_explorer.client import SchemaExplorerClient, connect
from mill.schema_explorer.dto import (
    ColumnDto,
    DataTypeDescriptor,
    FacetEnvelopeDto,
    FacetResolvedRowDto,
    ModelRootDto,
    SchemaContextDto,
    SchemaDto,
    SchemaExplorerTreeDto,
    SchemaListItemDto,
    ScopeOptionDto,
    TableDto,
    TableSummaryDto,
    column_dto_from_dict,
    data_type_descriptor_from_dict,
    facet_envelope_from_dict,
    facet_resolved_row_from_dict,
    model_root_from_dict,
    schema_context_from_dict,
    schema_dto_from_dict,
    schema_explorer_tree_from_dict,
    schema_list_item_from_dict,
    scope_option_from_dict,
    table_dto_from_dict,
    table_summary_from_dict,
)

__all__ = [
    "SchemaExplorerClient",
    "connect",
    "ColumnDto",
    "DataTypeDescriptor",
    "FacetEnvelopeDto",
    "FacetResolvedRowDto",
    "ModelRootDto",
    "SchemaContextDto",
    "SchemaDto",
    "SchemaExplorerTreeDto",
    "SchemaListItemDto",
    "ScopeOptionDto",
    "TableDto",
    "TableSummaryDto",
    "column_dto_from_dict",
    "data_type_descriptor_from_dict",
    "facet_envelope_from_dict",
    "facet_resolved_row_from_dict",
    "model_root_from_dict",
    "schema_context_from_dict",
    "schema_dto_from_dict",
    "schema_explorer_tree_from_dict",
    "schema_list_item_from_dict",
    "scope_option_from_dict",
    "table_dto_from_dict",
    "table_summary_from_dict",
]
