apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop
  namespace: qpointz
  labels:
    app: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
  template:
    metadata:
      namespace: qpointz
      labels:
        app: hadoop
    spec:
      volumes:
        - name: hadoop-storage
          persistentVolumeClaim:
            claimName: qpointz-data-volume-claim
      imagePullSecrets:
        - name: qpdockerkey
      containers:
        - name: hadoop-mini
          image: docker.qpointz.io/hadoop-unit:latest
          ports:
            #zookeper
            - containerPort: 22010
            #hdfs
            - containerPort: 20112
            - containerPort: 50070
            - containerPort: 50010
            - containerPort: 50075
            - containerPort: 50020
              #kafka
            - containerPort: 20111
              #hbase
            - containerPort: 25111
            - containerPort: 28000
            - containerPort: 28080
              #solr
            - containerPort: 8983
              #neo4j
            - containerPort:  13533
              #cassandra
            - containerPort:  13433
              #hivemeta
            - containerPort:  20102
              #hive2
            - containerPort:  20103
          volumeMounts:
            - mountPath: /data
              name: hadoop-storage
