apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: qpointz
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      namespace: qpointz
      labels:
        app: localstack
    spec:
      volumes:
        - name: localstack-storage
          persistentVolumeClaim:
            claimName: qpointz-data-volume-claim
      containers:
        - name: localstack
          image: localstack/localstack:latest
          ports:
            - containerPort: 4566
            - containerPort: 8080
          env:
            - name: LOCALSTACK_API_KEY
              value: 3ComflxqNA
            - name: EDGE_PORT
              value: "4566"
            - name: SERVICES
              value:  s3,iam,lambda,ec2
            - name: DOCKER_HOST
              value: "unix:///var/run/docker.sock"
            - name: HOST_TMP_FOLDER
              value: /data/localstack/tmp
            - name: DATA_DIR
              value: /data/localstack/data
            - name: DEFAULT_REGION
              value: us-east-1
          volumeMounts:
            - mountPath: /data
              name: localstack-storage