spec:
  inputs:
    package-local-only: 
      default: "true"
      description: "Package local only"
      options:  
        - "true"
        - "false"
---
include:  
  - local : /.gitlab/.common.yml

stages:  
  - build
  - package  

workflow:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"  
      variables: 
        PACKAGE_LOCAL_ONLY: "false"
    - when: always
      variables: 
        PACKAGE_LOCAL_ONLY: "true"

init-version:
  stage: build
  extends: .get-build-version

install-dist:
  extends: .gradle-job
  stage: build
  script:
    - cd ${CI_PROJECT_DIR}/apps
    - ./gradlew --no-daemon --console plain clean installBootDist assembleSamples
  artifacts:
    expire_in: "5 days"
    paths:
      - ${CI_PROJECT_DIR}/apps/mill-service/build/install/**/*

build-base-docker:
  stage: package
  extends: .docker-build-job
  needs:
    - job: install-dist
      artifacts: true
  variables:
    DOCKER_BUILD_CTX: ${CI_PROJECT_DIR}/apps/mill-service
    DOCKER_BUILD_FILE: ${CI_PROJECT_DIR}/apps/mill-service/src/main/docker/base/Dockerfile
    DOCKER_BUILD_CONTAINER_NAME : mill-service
    DOCKER_LOCAL_ONLY: $PACKAGE_LOCAL_ONLY

build-docker-samples:
  stage: package
  extends: .docker-build-job
  needs:
    - job: build-base-docker
      artifacts: false
    - job: install-dist
      artifacts: true
  variables:
    DOCKER_BUILD_CTX: ${CI_PROJECT_DIR}/apps/mill-service
    DOCKER_BUILD_FILE: ${CI_PROJECT_DIR}/apps/mill-service/src/main/docker/samples/Dockerfile
    DOCKER_BUILD_CONTAINER_NAME : mill-service-samples
    DOCKER_LOCAL_ONLY: $PACKAGE_LOCAL_ONLY
    DOCKER_BUILD_ARGS: --build-arg BASE_IMAGE=${CI_REGISTRY_IMAGE}/mill-service:${CI_COMMIT_REF_SLUG}