import type { MantineColorsTuple } from '@mantine/core';

export interface ColorTheme {
  id: string;
  name: string;
  mode: 'light' | 'dark';
  swatch: string;
  /** Accent palette (light → teal slot, dark → cyan slot) */
  colors: MantineColorsTuple;
  /** Tinted neutral palette (overrides `gray`). Tailwind-slate distribution.
   *  Generated by scripts/generate-neutrals.ts -- neutrals=0.18 */
  neutrals: MantineColorsTuple;
  /** Tinted dark palette (overrides `dark`). Mantine-dark distribution.
   *  Generated by scripts/generate-neutrals.ts -- darks=0.30 */
  darks: MantineColorsTuple;
}

// ---------------------------------------------------------------------------
// Light themes -- palette is used as the `teal` slot (light-mode accent).
// Neutrals override `gray`, darks override `dark`.
// ---------------------------------------------------------------------------

export const lightThemes: ColorTheme[] = [
  {
    id: 'classic',
    name: 'Classic',
    mode: 'light',
    swatch: '#14b8a6',
    colors: [
      '#f0fdfa', '#ccfbf1', '#99f6e4', '#5eead4', '#2dd4bf',
      '#14b8a6', '#0d9488', '#0f766e', '#115e59', '#134e4a',
    ],
    /** Original Tailwind slate palette — untinted, blue-toned gray */
    neutrals: [
      '#f8fafc', '#f1f5f9', '#e2e8f0', '#cbd5e1', '#94a3b8',
      '#64748b', '#475569', '#334155', '#1e293b', '#0f172a',
    ],
    /** Blue-tinted dark palette matching original slate look.
     *  dark-6 = slate-7, dark-7 = slate-8 (body), dark-8 = slate-9 (sidebar) */
    darks: [
      '#b9c3cf', '#9da8b7', '#8591a2', '#556377', '#3d4d62',
      '#364559', '#334155', '#1e293b', '#0f172a', '#0a101f',
    ],
  },
  {
    id: 'ocean',
    name: 'Ocean',
    mode: 'light',
    swatch: '#14b8a6',
    colors: [
      '#f0fdfa', '#ccfbf1', '#99f6e4', '#5eead4', '#2dd4bf',
      '#14b8a6', '#0d9488', '#0f766e', '#115e59', '#134e4a',
    ],
    neutrals: [
      '#f5fafb', '#eef6f9', '#e1eaf1', '#c9d8e3', '#8fabbc',
      '#5c7e91', '#425c6d', '#2f4758', '#1c2d3c', '#0e1a2a',
    ],
    darks: [
      '#bac9ca', '#9cb2b3', '#839fa0', '#516b6e', '#314145',
      '#273437', '#212b2e', '#171f20', '#121819', '#0e1314',
    ],
  },
  {
    id: 'forest',
    name: 'Forest',
    mode: 'light',
    swatch: '#16a34a',
    colors: [
      '#f0fdf4', '#dcfce7', '#bbf7d0', '#86efac', '#4ade80',
      '#22c55e', '#16a34a', '#15803d', '#166534', '#14532d',
    ],
    neutrals: [
      '#f5fafa', '#eef6f7', '#e1eaef', '#c9d8df', '#8faab4',
      '#5d7e87', '#425c66', '#304752', '#1c2d39', '#0e1a28',
    ],
    darks: [
      '#bac9c3', '#9db1a8', '#849e92', '#526a62', '#31413e',
      '#273431', '#212b29', '#171e1d', '#121816', '#0e1312',
    ],
  },
  {
    id: 'lavender',
    name: 'Lavender',
    mode: 'light',
    swatch: '#8b5cf6',
    colors: [
      '#f5f3ff', '#ede9fe', '#ddd6fe', '#c4b5fd', '#a78bfa',
      '#8b5cf6', '#7c3aed', '#6d28d9', '#5b21b6', '#4c1d95',
    ],
    neutrals: [
      '#f6f6fc', '#eff2f9', '#e2e6f1', '#cbd1e4', '#939bbe',
      '#626a94', '#464d6f', '#323b59', '#1e253e', '#0f152b',
    ],
    darks: [
      '#bebacd', '#a29cb6', '#8b84a4', '#585272', '#353247',
      '#2a2839', '#232130', '#191721', '#13121a', '#0f0f15',
    ],
  },
  {
    id: 'sunset',
    name: 'Sunset',
    mode: 'light',
    swatch: '#f59e0b',
    colors: [
      '#fffbeb', '#fef3c7', '#fde68a', '#fcd34d', '#fbbf24',
      '#f59e0b', '#d97706', '#b45309', '#92400e', '#78350f',
    ],
    neutrals: [
      '#f8f9fa', '#f1f5f7', '#e3e8ef', '#cdd5df', '#98a4b4',
      '#697586', '#4b5665', '#364252', '#202a39', '#111728',
    ],
    darks: [
      '#c4c3c2', '#aaa8a7', '#959391', '#616061', '#3a3b3d',
      '#2e2f31', '#272729', '#1b1b1d', '#151516', '#111112',
    ],
  },
];

// ---------------------------------------------------------------------------
// Dark themes -- palette is used as the `cyan` slot (dark-mode accent).
// Neutrals override `gray`, darks override `dark`.
// ---------------------------------------------------------------------------

export const darkThemes: ColorTheme[] = [
  {
    id: 'classic',
    name: 'Classic',
    mode: 'dark',
    swatch: '#22d3ee',
    colors: [
      '#ecfeff', '#cffafe', '#a5f3fc', '#67e8f9', '#22d3ee',
      '#06b6d4', '#0891b2', '#0e7490', '#155e75', '#164e63',
    ],
    /** Original Tailwind slate palette — untinted */
    neutrals: [
      '#f8fafc', '#f1f5f9', '#e2e8f0', '#cbd5e1', '#94a3b8',
      '#64748b', '#475569', '#334155', '#1e293b', '#0f172a',
    ],
    /** Blue-tinted dark palette matching original slate look.
     *  dark-6 = slate-7, dark-7 = slate-8 (body), dark-8 = slate-9 (sidebar) */
    darks: [
      '#b9c3cf', '#9da8b7', '#8591a2', '#556377', '#3d4d62',
      '#364559', '#334155', '#1e293b', '#0f172a', '#0a101f',
    ],
  },
  {
    id: 'neon',
    name: 'Neon',
    mode: 'dark',
    swatch: '#22d3ee',
    colors: [
      '#ecfeff', '#cffafe', '#a5f3fc', '#67e8f9', '#22d3ee',
      '#06b6d4', '#0891b2', '#0e7490', '#155e75', '#164e63',
    ],
    neutrals: [
      '#f4fafc', '#eef5f9', '#e1eaf1', '#c9d8e3', '#8ea9be',
      '#5c7c93', '#415b6f', '#2f4659', '#1c2c3d', '#0e192b',
    ],
    darks: [
      '#bac8cc', '#9bafb6', '#839ca4', '#506872', '#304047',
      '#263339', '#202a30', '#171e21', '#11171a', '#0e1315',
    ],
  },
  {
    id: 'aurora',
    name: 'Aurora',
    mode: 'dark',
    swatch: '#34d399',
    colors: [
      '#ecfdf5', '#d1fae5', '#a7f3d0', '#6ee7b7', '#34d399',
      '#10b981', '#059669', '#047857', '#065f46', '#064e3b',
    ],
    neutrals: [
      '#f5fafa', '#eff5f8', '#e1eaf0', '#cad8e1', '#90a9b8',
      '#5e7c8b', '#435b69', '#304655', '#1d2c3a', '#0f1929',
    ],
    darks: [
      '#bbc8c6', '#9eb0ad', '#869d98', '#536968', '#324041',
      '#283334', '#222a2c', '#181e1e', '#121717', '#0f1313',
    ],
  },
  {
    id: 'nebula',
    name: 'Nebula',
    mode: 'dark',
    swatch: '#c084fc',
    colors: [
      '#faf5ff', '#f3e8ff', '#e9d5ff', '#d8b4fe', '#c084fc',
      '#a855f7', '#9333ea', '#7e22ce', '#6b21a8', '#581c87',
    ],
    neutrals: [
      '#f6f6fc', '#f0f2fa', '#e3e6f1', '#ccd1e4', '#969bbf',
      '#666994', '#494d70', '#353b5a', '#1f253e', '#10152b',
    ],
    darks: [
      '#c1bacd', '#a69bb7', '#9083a5', '#5d5273', '#383248',
      '#2c2739', '#252130', '#1a1722', '#14121a', '#100f15',
    ],
  },
  {
    id: 'ember',
    name: 'Ember',
    mode: 'dark',
    swatch: '#fb923c',
    colors: [
      '#fff7ed', '#ffedd5', '#fed7aa', '#fdba74', '#fb923c',
      '#f97316', '#ea580c', '#c2410c', '#9a3412', '#7c2d12',
    ],
    neutrals: [
      '#f8f9fa', '#f2f4f7', '#e3e8ef', '#cdd5df', '#98a3b4',
      '#697486', '#4b5565', '#364152', '#202939', '#111728',
    ],
    darks: [
      '#c4c2c2', '#aaa7a7', '#959291', '#615f61', '#3a3a3d',
      '#2e2e31', '#272629', '#1b1b1d', '#151516', '#111112',
    ],
  },
];

export const DEFAULT_LIGHT_THEME_ID = 'classic';
export const DEFAULT_DARK_THEME_ID = 'classic';

export function findLightTheme(id: string): ColorTheme {
  return lightThemes.find((t) => t.id === id) ?? lightThemes[0]!;
}

export function findDarkTheme(id: string): ColorTheme {
  return darkThemes.find((t) => t.id === id) ?? darkThemes[0]!;
}
