logging:
  level:
    root: INFO
spring:
  main:
    web-application-type: none
    banner-mode: off
grpc:
  server:
    address: '*'
    port: 9099
    security:
      enabled: false

mill:
  backend:
    security:
      enabled: false
      providers: []