/* tslint:disable */
/* eslint-disable */
/**
 * Mill Metadata Service API
 * REST API for faceted metadata management with scope support
 *
 * The version of the OpenAPI document: v1
 * Contact: support@qpointz.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

