/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "services"

include (":mill-jet-http-service")
include (":mill-jet-grpc-service")
include (":mill-starter-service")
include (":mill-grinder-service")

includeBuild("../core") {
    dependencySubstitution {
        substitute(module("io.qpointz.mill:mill-starter-backends"))
            .using(project(":mill-starter-backends"))
        substitute(module("io.qpointz.mill:mill-service-core"))
            .using(project(":mill-service-core"))
        substitute(module("io.qpointz.mill:mill-security-core"))
            .using(project(":mill-security-core"))
        substitute(module("io.qpointz.mill:mill-starter-service"))
            .using(project(":mill-starter-service"))
    }
}

dependencyResolutionManagement {

    repositories {
        mavenCentral()
    }
    versionCatalogs {
        create("libs") {
            from(files("../libs.versions.toml"))
        }
    }
}

pluginManagement {
    includeBuild("../build-logic")

    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }

    plugins {
        kotlin("jvm") version "1.9.23"
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
}
