#
# Scala and sbt Dockerfile
#
# https://github.com/hseeberger/scala-sbt
#

# Pull base image
FROM node:21.7-alpine3.18

#RUN \
#  echo >> /root/.bashrc && \
#  echo 'export PATH=/data/.npm-global/bin:$PATH'>>/root/.bashrc

#RUN \
#    npm config set unsafe-perm true 

#COPY entrypoint.sh /root/entrypoint.sh

#RUN \
#    chmod +x /root/entrypoint.sh

#VOLUME /data

# Define working directory
#WORKDIR /root

#CMD /root/entrypoint.sh

