spring:
  profiles:
    include:
      - 'backend'
qp:
  mill:
    backend:
      security:
        enabled: false
      calcite:
        connection:
          quoting: BACK_TICK
          caseSensitive: true
          unquotedCasing: UNCHANGED
      jdbc:
        schema-name: jdbcinternalschema