image: ${CI_REGISTRY_IMAGE}/gradle-graalvm:$CI_COMMIT_REF_SLUG-ci
stages:
  - init
  - test
  - build
  - package


docker:buildImages:
  stage: init
  image:
    name: gcr.io/kaniko-project/executor:v1.16.0-debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - >
      echo "{ \"auths\":
        { \"$CI_REGISTRY\":{\"auth\":\"$(echo -n "${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}" | base64 )\"}
      }}" > /kaniko/.docker/.config.json
  script:
    - >
      /kaniko/executor  
      --context "${CI_PROJECT_DIR}/etc/docker/ci-graalvm"  
      --destination "${CI_REGISTRY_IMAGE}/gradle-graalvm:$CI_COMMIT_REF_SLUG-ci"  
      --cache=true

runTests:
  stage: test
  script:
    - gradle testCodeCoverageReport
  artifacts:
    reports:
      junit: ./**/*/build/test-results/test/*.xml
    paths:
      - ./**/*/build/reports/jacoco/testCodeCoverageReport/*.xml

runTestsIT:
  stage: test
  script:
    - gradle testITCodeCoverageReport
  artifacts:
    reports:
      junit: ./**/*/build/test-results/testIT/*.xml
    paths:
      - ./**/*/build/reports/jacoco/testITCodeCoverageReport/*.xml

buildJDBCDriver:
  stage: build
  script:
    - gradle shadowJar
  artifacts:
    paths:
      - ./rapids-jdbc-driver/build/libs/*-all.jar

buildRapidsApp:
  stage: build
  script:
    - gradle :rapids-srv-worker:bootstrapApp
  artifacts:
    paths:
      - ./rapids-srv-worker/build/rapids-app/*/*

buildRapidsDockerBranch:
  stage: package
  except:
    - main
    - dev
  dependencies:
    - buildRapidsApp
  image: docker:latest
  script:
    - echo "$NEXUS_PASSWORD" | docker login $DOCKER_REPO_CI  -u $NEXUS_USER --password-stdin
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u $DOCKER_HUB_USER --password-stdin
    - docker build -f ./rapids-srv-worker/src/main/docker/Dockerfile -t docker-ci.qpointz.io/rapids-worker:$CI_COMMIT_REF_SLUG -t qpointz/rapids-worker:$CI_COMMIT_REF_SLUG .
    - docker push docker-ci.qpointz.io/rapids-worker:$CI_COMMIT_REF_SLUG
    - docker push qpointz/rapids-worker:$CI_COMMIT_REF_SLUG