grpc:
  server:
    port: ${mill.data.services.grpc.port}
#    address: ${mill.data.services.grpc.address}


spring:
  application:
    name: ${mill.application.name}
  main:
    web-application-type: servlet
  datasource:
    url: "jdbc:h2:mem:mill-moneta;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH"
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

mill:
  application:
    name: mill-service
    hosts:
      externals:
        http:
          scheme: http
          host: localhost
          port: 8080
        grpc:
          scheme: grpc
          host: localhost
          port: 9090
  data:
    services:
      grpc:
        enable: true
        external-host: grpc
        port: 9090
      http:
        enable: true
        external-host: http
        port: 8080
## LEGACY subject to review
  security:
    enable: false
  metadata:
    repository:
      type: jpa
    facet-type-registry:
      type: local
    seed:
      resources:
        - "classpath:metadata/platform-bootstrap.yaml"
        - "classpath:metadata/platform-flow-facet-types.yaml"
  services:
    ai-nl2data:
      enable: false

springdoc:
  swagger-ui:
    tags-sorter: alpha
