include:
  - local : /.gitlab/vars.yml
  - local : /.gitlab/jobs.yml

image: ${CI_IMAGE_GRADLE}

#variables:
#  PROTOC_SRC : rapids/rapids-grpc/src/main/proto
#  PROTOC_OUT : rapids/build/protoc

stages:  
  - test
  - build
  - package
  - contrib-test
  - check

workflow:
  rules:
    - when : always

delta:unit-tests:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}/delta
    - gradle clean test testCodeCoverage jacocoTestReport
  artifacts:
    when: always
    reports:
      junit: ${CI_PROJECT_DIR}/delta/*/build/test-results/test/*.xml
    paths:
      - ${CI_PROJECT_DIR}/delta/*/build/test-results/test/*.xml


sonarqube-check:
  stage: check  
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/delta/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
    SONAR_TOKEN: ${SONAR_DELTA_TOKEN}
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd ${CI_PROJECT_DIR}/delta
    - gradle clean test jacocoTestReport  jacocoTestReport sonar
  allow_failure: true
  only:
    - dev