version: '2'
services:
  mill-backend:
    image: registry.qpointz.io/qpointz/qpointz/mill-calcite-backend:v0.2.0-dev
    ports:
      - "9099:9099"
    environment:
      - QP_MILL_BACKEND_SECURITY_ENABLED=false
  