spring:
  application:
    name: delta-calcite
  main:
    web-application-type: none
    banner-mode: off
grpc:
  server:
    address: '*'
    port: 9099
    security:
      enabled: false
calcite:
  connection:
    quoting: BACK_TICK
    caseSensitive: true
    unquotedCasing: UNCHANGED