/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ApplicationDescriptor
 */
export interface ApplicationDescriptor {
    /**
     * 
     * @type {Array<ServiceDescriptor>}
     * @memberof ApplicationDescriptor
     */
    'services'?: Array<ServiceDescriptor>;
    /**
     * 
     * @type {SecurityDescriptor}
     * @memberof ApplicationDescriptor
     */
    'security'?: SecurityDescriptor;
    /**
     * 
     * @type {{ [key: string]: SchemaDescriptor; }}
     * @memberof ApplicationDescriptor
     */
    'schemas'?: { [key: string]: SchemaDescriptor; };
}
/**
 * 
 * @export
 * @interface Chat
 */
export interface Chat {
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Chat
     */
    'isFavorite'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    'created'?: string;
}
/**
 * 
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    'role'?: ChatMessageRoleEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ChatMessage
     */
    'content'?: { [key: string]: any; };
}

export const ChatMessageRoleEnum = {
    User: 'USER',
    Chat: 'CHAT',
    System: 'SYSTEM'
} as const;

export type ChatMessageRoleEnum = typeof ChatMessageRoleEnum[keyof typeof ChatMessageRoleEnum];

/**
 * 
 * @export
 * @interface CreateChatRequest
 */
export interface CreateChatRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateChatRequest
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface SchemaDescriptor
 */
export interface SchemaDescriptor {
    /**
     * 
     * @type {string}
     * @memberof SchemaDescriptor
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaDescriptor
     */
    'link'?: string;
}
/**
 * 
 * @export
 * @interface SecurityDescriptor
 */
export interface SecurityDescriptor {
    /**
     * 
     * @type {boolean}
     * @memberof SecurityDescriptor
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {Set<string>}
     * @memberof SecurityDescriptor
     */
    'authMethods'?: Set<SecurityDescriptorAuthMethodsEnum>;
}

export const SecurityDescriptorAuthMethodsEnum = {
    Custom: 'CUSTOM',
    Oauth2: 'OAUTH2',
    Basic: 'BASIC'
} as const;

export type SecurityDescriptorAuthMethodsEnum = typeof SecurityDescriptorAuthMethodsEnum[keyof typeof SecurityDescriptorAuthMethodsEnum];

/**
 * 
 * @export
 * @interface SendChatMessageRequest
 */
export interface SendChatMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageRequest
     */
    'message'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SendChatMessageRequest
     */
    'content'?: { [key: string]: any; };
}
/**
 * 
 * @export
 * @interface ServiceDescriptor
 */
export interface ServiceDescriptor {
    /**
     * 
     * @type {string}
     * @memberof ServiceDescriptor
     */
    'stereotype'?: string;
}
/**
 * 
 * @export
 * @interface UpdateChatRequest
 */
export interface UpdateChatRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateChatRequest
     */
    'chatName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateChatRequest
     */
    'isFavorite'?: boolean;
}

/**
 * ApplicationDescriptorControllerApi - axios parameter creator
 * @export
 */
export const ApplicationDescriptorControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/.well-known/mill`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApplicationDescriptorControllerApi - functional programming interface
 * @export
 */
export const ApplicationDescriptorControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApplicationDescriptorControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApplicationDescriptor>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApplicationDescriptorControllerApi.getInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ApplicationDescriptorControllerApi - factory interface
 * @export
 */
export const ApplicationDescriptorControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApplicationDescriptorControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInfo(options?: RawAxiosRequestConfig): AxiosPromise<ApplicationDescriptor> {
            return localVarFp.getInfo(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApplicationDescriptorControllerApi - object-oriented interface
 * @export
 * @class ApplicationDescriptorControllerApi
 * @extends {BaseAPI}
 */
export class ApplicationDescriptorControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicationDescriptorControllerApi
     */
    public getInfo(options?: RawAxiosRequestConfig) {
        return ApplicationDescriptorControllerApiFp(this.configuration).getInfo(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * NlSqlChatControllerApi - axios parameter creator
 * @export
 */
export const NlSqlChatControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatStream: async (chatId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('chatStream', 'chatId', chatId)
            const localVarPath = `/api/nl2sql/chats/{chatId}/stream`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates new chat
         * @param {CreateChatRequest} createChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createChat: async (createChatRequest: CreateChatRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createChatRequest' is not null or undefined
            assertParamExists('createChat', 'createChatRequest', createChatRequest)
            const localVarPath = `/api/nl2sql/chats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createChatRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteChat: async (chatId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('deleteChat', 'chatId', chatId)
            const localVarPath = `/api/nl2sql/chats/{chatId}`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChat: async (chatId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('getChat', 'chatId', chatId)
            const localVarPath = `/api/nl2sql/chats/{chatId}`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChatMessages: async (chatId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('listChatMessages', 'chatId', chatId)
            const localVarPath = `/api/nl2sql/chats/{chatId}/messages`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChats: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/nl2sql/chats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} chatId 
         * @param {SendChatMessageRequest} sendChatMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postChatMessages: async (chatId: string, sendChatMessageRequest: SendChatMessageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('postChatMessages', 'chatId', chatId)
            // verify required parameter 'sendChatMessageRequest' is not null or undefined
            assertParamExists('postChatMessages', 'sendChatMessageRequest', sendChatMessageRequest)
            const localVarPath = `/api/nl2sql/chats/{chatId}/messages`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendChatMessageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} chatId 
         * @param {UpdateChatRequest} arg1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateChat: async (chatId: string, arg1: UpdateChatRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('updateChat', 'chatId', chatId)
            // verify required parameter 'arg1' is not null or undefined
            assertParamExists('updateChat', 'arg1', arg1)
            const localVarPath = `/api/nl2sql/chats/{chatId}`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (arg1 !== undefined) {
                for (const [key, value] of Object.entries(arg1)) {
                    localVarQueryParameter[key] = value;
                }
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NlSqlChatControllerApi - functional programming interface
 * @export
 */
export const NlSqlChatControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NlSqlChatControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatStream(chatId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<any>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatStream(chatId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.chatStream']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates new chat
         * @param {CreateChatRequest} createChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createChat(createChatRequest: CreateChatRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Chat>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createChat(createChatRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.createChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteChat(chatId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteChat(chatId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.deleteChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getChat(chatId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Chat>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getChat(chatId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.getChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listChatMessages(chatId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ChatMessage>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listChatMessages(chatId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.listChatMessages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listChats(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Chat>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listChats(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.listChats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} chatId 
         * @param {SendChatMessageRequest} sendChatMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postChatMessages(chatId: string, sendChatMessageRequest: SendChatMessageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postChatMessages(chatId, sendChatMessageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.postChatMessages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} chatId 
         * @param {UpdateChatRequest} arg1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateChat(chatId: string, arg1: UpdateChatRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Chat>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateChat(chatId, arg1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.updateChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NlSqlChatControllerApi - factory interface
 * @export
 */
export const NlSqlChatControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NlSqlChatControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatStream(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<any>> {
            return localVarFp.chatStream(chatId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates new chat
         * @param {CreateChatRequest} createChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createChat(createChatRequest: CreateChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<Chat> {
            return localVarFp.createChat(createChatRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteChat(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteChat(chatId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChat(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<Chat> {
            return localVarFp.getChat(chatId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChatMessages(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ChatMessage>> {
            return localVarFp.listChatMessages(chatId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChats(options?: RawAxiosRequestConfig): AxiosPromise<Array<Chat>> {
            return localVarFp.listChats(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} chatId 
         * @param {SendChatMessageRequest} sendChatMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postChatMessages(chatId: string, sendChatMessageRequest: SendChatMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<ChatMessage> {
            return localVarFp.postChatMessages(chatId, sendChatMessageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} chatId 
         * @param {UpdateChatRequest} arg1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateChat(chatId: string, arg1: UpdateChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<Chat> {
            return localVarFp.updateChat(chatId, arg1, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NlSqlChatControllerApi - object-oriented interface
 * @export
 * @class NlSqlChatControllerApi
 * @extends {BaseAPI}
 */
export class NlSqlChatControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public chatStream(chatId: string, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).chatStream(chatId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates new chat
     * @param {CreateChatRequest} createChatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public createChat(createChatRequest: CreateChatRequest, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).createChat(createChatRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public deleteChat(chatId: string, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).deleteChat(chatId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public getChat(chatId: string, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).getChat(chatId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public listChatMessages(chatId: string, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).listChatMessages(chatId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public listChats(options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).listChats(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} chatId 
     * @param {SendChatMessageRequest} sendChatMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public postChatMessages(chatId: string, sendChatMessageRequest: SendChatMessageRequest, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).postChatMessages(chatId, sendChatMessageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} chatId 
     * @param {UpdateChatRequest} arg1 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public updateChat(chatId: string, arg1: UpdateChatRequest, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).updateChat(chatId, arg1, options).then((request) => request(this.axios, this.basePath));
    }
}



