/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ApplicationDescriptor
 */
export interface ApplicationDescriptor {
    /**
     * 
     * @type {Array<ServiceDescriptor>}
     * @memberof ApplicationDescriptor
     */
    'services'?: Array<ServiceDescriptor>;
    /**
     * 
     * @type {SecurityDescriptor}
     * @memberof ApplicationDescriptor
     */
    'security'?: SecurityDescriptor;
    /**
     * 
     * @type {{ [key: string]: SchemaDescriptor; }}
     * @memberof ApplicationDescriptor
     */
    'schemas'?: { [key: string]: SchemaDescriptor; };
}
/**
 * 
 * @export
 * @interface AuthenticationMethodDescriptor
 */
export interface AuthenticationMethodDescriptor {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationMethodDescriptor
     */
    'authType'?: AuthenticationMethodDescriptorAuthTypeEnum;
}

export const AuthenticationMethodDescriptorAuthTypeEnum = {
    Custom: 'CUSTOM',
    Oauth2: 'OAUTH2',
    Basic: 'BASIC'
} as const;

export type AuthenticationMethodDescriptorAuthTypeEnum = typeof AuthenticationMethodDescriptorAuthTypeEnum[keyof typeof AuthenticationMethodDescriptorAuthTypeEnum];

/**
 * 
 * @export
 * @interface Chat
 */
export interface Chat {
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Chat
     */
    'isFavorite'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Chat
     */
    'created'?: string;
}
/**
 * 
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    'role'?: ChatMessageRoleEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ChatMessage
     */
    'content'?: { [key: string]: any; };
}

export const ChatMessageRoleEnum = {
    User: 'USER',
    Chat: 'CHAT',
    System: 'SYSTEM'
} as const;

export type ChatMessageRoleEnum = typeof ChatMessageRoleEnum[keyof typeof ChatMessageRoleEnum];

/**
 * 
 * @export
 * @interface ContentDisposition
 */
export interface ContentDisposition {
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     */
    'filename'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     */
    'charset'?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentDisposition
     * @deprecated
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     * @deprecated
     */
    'creationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     * @deprecated
     */
    'modificationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentDisposition
     * @deprecated
     */
    'readDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContentDisposition
     */
    'inline'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContentDisposition
     */
    'formData'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContentDisposition
     */
    'attachment'?: boolean;
}
/**
 * 
 * @export
 * @interface CreateChatRequest
 */
export interface CreateChatRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateChatRequest
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface DefaultHttpStatusCode
 */
export interface DefaultHttpStatusCode {
    /**
     * 
     * @type {boolean}
     * @memberof DefaultHttpStatusCode
     */
    'error'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DefaultHttpStatusCode
     */
    'is5xxServerError'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DefaultHttpStatusCode
     */
    'is4xxClientError'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DefaultHttpStatusCode
     */
    'is2xxSuccessful'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DefaultHttpStatusCode
     */
    'is3xxRedirection'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DefaultHttpStatusCode
     */
    'is1xxInformational'?: boolean;
}
/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'typeMessageCode'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof ErrorResponse
     */
    'detailMessageArguments'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'titleMessageCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'detailMessageCode'?: string;
    /**
     * 
     * @type {ErrorResponseHeaders}
     * @memberof ErrorResponse
     */
    'headers'?: ErrorResponseHeaders;
    /**
     * 
     * @type {ErrorResponseStatusCode}
     * @memberof ErrorResponse
     */
    'statusCode'?: ErrorResponseStatusCode;
    /**
     * 
     * @type {ProblemDetail}
     * @memberof ErrorResponse
     */
    'body'?: ProblemDetail;
}
/**
 * 
 * @export
 * @interface ErrorResponseHeaders
 */
export interface ErrorResponseHeaders {
    [key: string]: Array<string> | any;

    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'origin'?: string;
    /**
     * 
     * @type {MediaType}
     * @memberof ErrorResponseHeaders
     */
    'contentType'?: MediaType;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'connection'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeaders
     */
    'empty'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'location'?: string;
    /**
     * 
     * @type {ErrorResponseHeadersHost}
     * @memberof ErrorResponseHeaders
     */
    'host'?: ErrorResponseHeadersHost;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ErrorResponseHeaders
     */
    'all'?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'lastModified'?: number;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'date'?: number;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'contentLength'?: number;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'ifModifiedSince'?: number;
    /**
     * 
     * @type {Array<any>}
     * @memberof ErrorResponseHeaders
     */
    'range'?: Array<any>;
    /**
     * 
     * @type {ContentDisposition}
     * @memberof ErrorResponseHeaders
     */
    'contentDisposition'?: ContentDisposition;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'acceptCharset'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'bearerAuth'?: string;
    /**
     * 
     * @type {Set<any>}
     * @memberof ErrorResponseHeaders
     */
    'allow'?: Set<any>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'cacheControl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'contentLanguage'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'etag'?: string;
    /**
     * 
     * @type {Array<ErrorResponseHeadersAcceptLanguageInner>}
     * @memberof ErrorResponseHeaders
     */
    'acceptLanguage'?: Array<ErrorResponseHeadersAcceptLanguageInner>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'basicAuth'?: string;
    /**
     * 
     * @type {Array<MediaType>}
     * @memberof ErrorResponseHeaders
     */
    'accept'?: Array<MediaType>;
    /**
     * 
     * @type {Array<MediaType>}
     * @memberof ErrorResponseHeaders
     */
    'acceptPatch'?: Array<MediaType>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'ifNoneMatch'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'pragma'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'upgrade'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'vary'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'expires'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'ifMatch'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'accessControlMaxAge'?: number;
    /**
     * 
     * @type {any}
     * @memberof ErrorResponseHeaders
     */
    'accessControlRequestMethod'?: any;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeaders
     */
    'ifUnmodifiedSince'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'accessControlRequestHeaders'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'acceptLanguageAsLocales'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeaders
     */
    'accessControlAllowCredentials'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'accessControlAllowHeaders'?: Array<string>;
    /**
     * 
     * @type {Array<any>}
     * @memberof ErrorResponseHeaders
     */
    'accessControlAllowMethods'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeaders
     */
    'accessControlAllowOrigin'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseHeaders
     */
    'accessControlExposeHeaders'?: Array<string>;
}
/**
 * 
 * @export
 * @interface ErrorResponseHeadersAcceptLanguageInner
 */
export interface ErrorResponseHeadersAcceptLanguageInner {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersAcceptLanguageInner
     */
    'range'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeadersAcceptLanguageInner
     */
    'weight'?: number;
}
/**
 * 
 * @export
 * @interface ErrorResponseHeadersHost
 */
export interface ErrorResponseHeadersHost {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHost
     */
    'hostString'?: string;
    /**
     * 
     * @type {ErrorResponseHeadersHostAddress}
     * @memberof ErrorResponseHeadersHost
     */
    'address'?: ErrorResponseHeadersHostAddress;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseHeadersHost
     */
    'port'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHost
     */
    'unresolved'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHost
     */
    'hostName'?: string;
}
/**
 * 
 * @export
 * @interface ErrorResponseHeadersHostAddress
 */
export interface ErrorResponseHeadersHostAddress {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'hostAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'hostName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'linkLocalAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'multicastAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'anyLocalAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'loopbackAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'siteLocalAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'mcglobal'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'mcnodeLocal'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'mclinkLocal'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'mcsiteLocal'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'mcorgLocal'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseHeadersHostAddress
     */
    'canonicalHostName'?: string;
}
/**
 * @type ErrorResponseStatusCode
 * @export
 */
export type ErrorResponseStatusCode = DefaultHttpStatusCode | HttpStatus;

/**
 * 
 * @export
 * @enum {HttpStatusCode}
 */

export const HttpStatus = {
    _100Continue: '100 CONTINUE',
    _101SwitchingProtocols: '101 SWITCHING_PROTOCOLS',
    _102Processing: '102 PROCESSING',
    _103EarlyHints: '103 EARLY_HINTS',
    _103Checkpoint: '103 CHECKPOINT',
    _200Ok: '200 OK',
    _201Created: '201 CREATED',
    _202Accepted: '202 ACCEPTED',
    _203NonAuthoritativeInformation: '203 NON_AUTHORITATIVE_INFORMATION',
    _204NoContent: '204 NO_CONTENT',
    _205ResetContent: '205 RESET_CONTENT',
    _206PartialContent: '206 PARTIAL_CONTENT',
    _207MultiStatus: '207 MULTI_STATUS',
    _208AlreadyReported: '208 ALREADY_REPORTED',
    _226ImUsed: '226 IM_USED',
    _300MultipleChoices: '300 MULTIPLE_CHOICES',
    _301MovedPermanently: '301 MOVED_PERMANENTLY',
    _302Found: '302 FOUND',
    _302MovedTemporarily: '302 MOVED_TEMPORARILY',
    _303SeeOther: '303 SEE_OTHER',
    _304NotModified: '304 NOT_MODIFIED',
    _305UseProxy: '305 USE_PROXY',
    _307TemporaryRedirect: '307 TEMPORARY_REDIRECT',
    _308PermanentRedirect: '308 PERMANENT_REDIRECT',
    _400BadRequest: '400 BAD_REQUEST',
    _401Unauthorized: '401 UNAUTHORIZED',
    _402PaymentRequired: '402 PAYMENT_REQUIRED',
    _403Forbidden: '403 FORBIDDEN',
    _404NotFound: '404 NOT_FOUND',
    _405MethodNotAllowed: '405 METHOD_NOT_ALLOWED',
    _406NotAcceptable: '406 NOT_ACCEPTABLE',
    _407ProxyAuthenticationRequired: '407 PROXY_AUTHENTICATION_REQUIRED',
    _408RequestTimeout: '408 REQUEST_TIMEOUT',
    _409Conflict: '409 CONFLICT',
    _410Gone: '410 GONE',
    _411LengthRequired: '411 LENGTH_REQUIRED',
    _412PreconditionFailed: '412 PRECONDITION_FAILED',
    _413PayloadTooLarge: '413 PAYLOAD_TOO_LARGE',
    _413RequestEntityTooLarge: '413 REQUEST_ENTITY_TOO_LARGE',
    _414UriTooLong: '414 URI_TOO_LONG',
    _414RequestUriTooLong: '414 REQUEST_URI_TOO_LONG',
    _415UnsupportedMediaType: '415 UNSUPPORTED_MEDIA_TYPE',
    _416RequestedRangeNotSatisfiable: '416 REQUESTED_RANGE_NOT_SATISFIABLE',
    _417ExpectationFailed: '417 EXPECTATION_FAILED',
    _418IAmATeapot: '418 I_AM_A_TEAPOT',
    _419InsufficientSpaceOnResource: '419 INSUFFICIENT_SPACE_ON_RESOURCE',
    _420MethodFailure: '420 METHOD_FAILURE',
    _421DestinationLocked: '421 DESTINATION_LOCKED',
    _422UnprocessableEntity: '422 UNPROCESSABLE_ENTITY',
    _423Locked: '423 LOCKED',
    _424FailedDependency: '424 FAILED_DEPENDENCY',
    _425TooEarly: '425 TOO_EARLY',
    _426UpgradeRequired: '426 UPGRADE_REQUIRED',
    _428PreconditionRequired: '428 PRECONDITION_REQUIRED',
    _429TooManyRequests: '429 TOO_MANY_REQUESTS',
    _431RequestHeaderFieldsTooLarge: '431 REQUEST_HEADER_FIELDS_TOO_LARGE',
    _451UnavailableForLegalReasons: '451 UNAVAILABLE_FOR_LEGAL_REASONS',
    _500InternalServerError: '500 INTERNAL_SERVER_ERROR',
    _501NotImplemented: '501 NOT_IMPLEMENTED',
    _502BadGateway: '502 BAD_GATEWAY',
    _503ServiceUnavailable: '503 SERVICE_UNAVAILABLE',
    _504GatewayTimeout: '504 GATEWAY_TIMEOUT',
    _505HttpVersionNotSupported: '505 HTTP_VERSION_NOT_SUPPORTED',
    _506VariantAlsoNegotiates: '506 VARIANT_ALSO_NEGOTIATES',
    _507InsufficientStorage: '507 INSUFFICIENT_STORAGE',
    _508LoopDetected: '508 LOOP_DETECTED',
    _509BandwidthLimitExceeded: '509 BANDWIDTH_LIMIT_EXCEEDED',
    _510NotExtended: '510 NOT_EXTENDED',
    _511NetworkAuthenticationRequired: '511 NETWORK_AUTHENTICATION_REQUIRED'
} as const;

export type HttpStatus = typeof HttpStatus[keyof typeof HttpStatus];


/**
 * 
 * @export
 * @interface HttpStatusCode
 */
export interface HttpStatusCode {
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'error'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'is5xxServerError'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'is4xxClientError'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'is2xxSuccessful'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'is3xxRedirection'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HttpStatusCode
     */
    'is1xxInformational'?: boolean;
}
/**
 * 
 * @export
 * @interface MediaType
 */
export interface MediaType {
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    'subtype'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MediaType
     */
    'parameters'?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof MediaType
     */
    'qualityValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    'charset'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MediaType
     */
    'concrete'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MediaType
     */
    'wildcardSubtype'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MediaType
     */
    'wildcardType'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    'subtypeSuffix'?: string;
}
/**
 * 
 * @export
 * @interface ProblemDetail
 */
export interface ProblemDetail {
    /**
     * 
     * @type {string}
     * @memberof ProblemDetail
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetail
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProblemDetail
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetail
     */
    'detail'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetail
     */
    'instance'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProblemDetail
     */
    'properties'?: { [key: string]: any; };
}
/**
 * 
 * @export
 * @interface SchemaDescriptor
 */
export interface SchemaDescriptor {
    /**
     * 
     * @type {string}
     * @memberof SchemaDescriptor
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaDescriptor
     */
    'link'?: string;
}
/**
 * 
 * @export
 * @interface SecurityDescriptor
 */
export interface SecurityDescriptor {
    /**
     * 
     * @type {boolean}
     * @memberof SecurityDescriptor
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {Array<AuthenticationMethodDescriptor>}
     * @memberof SecurityDescriptor
     */
    'authMethods'?: Array<AuthenticationMethodDescriptor>;
}
/**
 * 
 * @export
 * @interface SendChatMessageRequest
 */
export interface SendChatMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageRequest
     */
    'message'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SendChatMessageRequest
     */
    'content'?: { [key: string]: any; };
}
/**
 * 
 * @export
 * @interface ServiceDescriptor
 */
export interface ServiceDescriptor {
    /**
     * 
     * @type {string}
     * @memberof ServiceDescriptor
     */
    'stereotype'?: string;
}
/**
 * 
 * @export
 * @interface UpdateChatRequest
 */
export interface UpdateChatRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateChatRequest
     */
    'chatName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateChatRequest
     */
    'isFavorite'?: boolean;
}

/**
 * AccessServiceControllerApi - axios parameter creator
 * @export
 */
export const AccessServiceControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchQueryResult: async (body: string, accept?: string, contentType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('fetchQueryResult', 'body', body)
            const localVarPath = `/services/jet/FetchQueryResult`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchema: async (body: string, accept?: string, contentType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('getSchema', 'body', body)
            const localVarPath = `/services/jet/GetSchema`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handshake: async (accept?: string, contentType?: string, body?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/services/jet/Handshake`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSchemas: async (accept?: string, contentType?: string, body?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/services/jet/ListSchemas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        parseSql: async (body: string, accept?: string, contentType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('parseSql', 'body', body)
            const localVarPath = `/services/jet/ParseSql`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitQuery: async (body: string, accept?: string, contentType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('submitQuery', 'body', body)
            const localVarPath = `/services/jet/SubmitQuery`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccessServiceControllerApi - functional programming interface
 * @export
 */
export const AccessServiceControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccessServiceControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchQueryResult(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchQueryResult(body, accept, contentType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccessServiceControllerApi.fetchQueryResult']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSchema(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSchema(body, accept, contentType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccessServiceControllerApi.getSchema']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async handshake(accept?: string, contentType?: string, body?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.handshake(accept, contentType, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccessServiceControllerApi.handshake']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSchemas(accept?: string, contentType?: string, body?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSchemas(accept, contentType, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccessServiceControllerApi.listSchemas']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async parseSql(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.parseSql(body, accept, contentType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccessServiceControllerApi.parseSql']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitQuery(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitQuery(body, accept, contentType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccessServiceControllerApi.submitQuery']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccessServiceControllerApi - factory interface
 * @export
 */
export const AccessServiceControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccessServiceControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchQueryResult(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.fetchQueryResult(body, accept, contentType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchema(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.getSchema(body, accept, contentType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handshake(accept?: string, contentType?: string, body?: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.handshake(accept, contentType, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSchemas(accept?: string, contentType?: string, body?: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.listSchemas(accept, contentType, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        parseSql(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.parseSql(body, accept, contentType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} body 
         * @param {string} [accept] 
         * @param {string} [contentType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitQuery(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.submitQuery(body, accept, contentType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccessServiceControllerApi - interface
 * @export
 * @interface AccessServiceControllerApi
 */
export interface AccessServiceControllerApiInterface {
    /**
     * 
     * @param {string} body 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApiInterface
     */
    fetchQueryResult(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * 
     * @param {string} body 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApiInterface
     */
    getSchema(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApiInterface
     */
    handshake(accept?: string, contentType?: string, body?: string, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApiInterface
     */
    listSchemas(accept?: string, contentType?: string, body?: string, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * 
     * @param {string} body 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApiInterface
     */
    parseSql(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * 
     * @param {string} body 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApiInterface
     */
    submitQuery(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig): AxiosPromise<object>;

}

/**
 * AccessServiceControllerApi - object-oriented interface
 * @export
 * @class AccessServiceControllerApi
 * @extends {BaseAPI}
 */
export class AccessServiceControllerApi extends BaseAPI implements AccessServiceControllerApiInterface {
    /**
     * 
     * @param {string} body 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApi
     */
    public fetchQueryResult(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig) {
        return AccessServiceControllerApiFp(this.configuration).fetchQueryResult(body, accept, contentType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} body 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApi
     */
    public getSchema(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig) {
        return AccessServiceControllerApiFp(this.configuration).getSchema(body, accept, contentType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApi
     */
    public handshake(accept?: string, contentType?: string, body?: string, options?: RawAxiosRequestConfig) {
        return AccessServiceControllerApiFp(this.configuration).handshake(accept, contentType, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApi
     */
    public listSchemas(accept?: string, contentType?: string, body?: string, options?: RawAxiosRequestConfig) {
        return AccessServiceControllerApiFp(this.configuration).listSchemas(accept, contentType, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} body 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApi
     */
    public parseSql(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig) {
        return AccessServiceControllerApiFp(this.configuration).parseSql(body, accept, contentType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} body 
     * @param {string} [accept] 
     * @param {string} [contentType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessServiceControllerApi
     */
    public submitQuery(body: string, accept?: string, contentType?: string, options?: RawAxiosRequestConfig) {
        return AccessServiceControllerApiFp(this.configuration).submitQuery(body, accept, contentType, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ApplicationDescriptorControllerApi - axios parameter creator
 * @export
 */
export const ApplicationDescriptorControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/.well-known/mill`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApplicationDescriptorControllerApi - functional programming interface
 * @export
 */
export const ApplicationDescriptorControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApplicationDescriptorControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApplicationDescriptor>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApplicationDescriptorControllerApi.getInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ApplicationDescriptorControllerApi - factory interface
 * @export
 */
export const ApplicationDescriptorControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApplicationDescriptorControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInfo(options?: RawAxiosRequestConfig): AxiosPromise<ApplicationDescriptor> {
            return localVarFp.getInfo(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApplicationDescriptorControllerApi - interface
 * @export
 * @interface ApplicationDescriptorControllerApi
 */
export interface ApplicationDescriptorControllerApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicationDescriptorControllerApiInterface
     */
    getInfo(options?: RawAxiosRequestConfig): AxiosPromise<ApplicationDescriptor>;

}

/**
 * ApplicationDescriptorControllerApi - object-oriented interface
 * @export
 * @class ApplicationDescriptorControllerApi
 * @extends {BaseAPI}
 */
export class ApplicationDescriptorControllerApi extends BaseAPI implements ApplicationDescriptorControllerApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicationDescriptorControllerApi
     */
    public getInfo(options?: RawAxiosRequestConfig) {
        return ApplicationDescriptorControllerApiFp(this.configuration).getInfo(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * NlSqlChatControllerApi - axios parameter creator
 * @export
 */
export const NlSqlChatControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatStream: async (chatId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('chatStream', 'chatId', chatId)
            const localVarPath = `/api/nl2sql/chats/{chatId}/stream`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates new chat
         * @param {CreateChatRequest} createChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createChat: async (createChatRequest: CreateChatRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createChatRequest' is not null or undefined
            assertParamExists('createChat', 'createChatRequest', createChatRequest)
            const localVarPath = `/api/nl2sql/chats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createChatRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes chat chat
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteChat: async (chatId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('deleteChat', 'chatId', chatId)
            const localVarPath = `/api/nl2sql/chats/{chatId}`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChat: async (chatId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('getChat', 'chatId', chatId)
            const localVarPath = `/api/nl2sql/chats/{chatId}`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChatMessages: async (chatId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('listChatMessages', 'chatId', chatId)
            const localVarPath = `/api/nl2sql/chats/{chatId}/messages`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChats: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/nl2sql/chats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} chatId 
         * @param {SendChatMessageRequest} sendChatMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postChatMessages: async (chatId: string, sendChatMessageRequest: SendChatMessageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('postChatMessages', 'chatId', chatId)
            // verify required parameter 'sendChatMessageRequest' is not null or undefined
            assertParamExists('postChatMessages', 'sendChatMessageRequest', sendChatMessageRequest)
            const localVarPath = `/api/nl2sql/chats/{chatId}/messages`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendChatMessageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates chat
         * @param {string} chatId 
         * @param {UpdateChatRequest} updateChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateChat: async (chatId: string, updateChatRequest: UpdateChatRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatId' is not null or undefined
            assertParamExists('updateChat', 'chatId', chatId)
            // verify required parameter 'updateChatRequest' is not null or undefined
            assertParamExists('updateChat', 'updateChatRequest', updateChatRequest)
            const localVarPath = `/api/nl2sql/chats/{chatId}`
                .replace(`{${"chatId"}}`, encodeURIComponent(String(chatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateChatRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NlSqlChatControllerApi - functional programming interface
 * @export
 */
export const NlSqlChatControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NlSqlChatControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatStream(chatId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<any>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatStream(chatId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.chatStream']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates new chat
         * @param {CreateChatRequest} createChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createChat(createChatRequest: CreateChatRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Chat>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createChat(createChatRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.createChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deletes chat chat
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteChat(chatId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteChat(chatId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.deleteChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getChat(chatId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Chat>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getChat(chatId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.getChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listChatMessages(chatId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ChatMessage>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listChatMessages(chatId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.listChatMessages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listChats(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Chat>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listChats(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.listChats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} chatId 
         * @param {SendChatMessageRequest} sendChatMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postChatMessages(chatId: string, sendChatMessageRequest: SendChatMessageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postChatMessages(chatId, sendChatMessageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.postChatMessages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Updates chat
         * @param {string} chatId 
         * @param {UpdateChatRequest} updateChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateChat(chatId: string, updateChatRequest: UpdateChatRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Chat>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateChat(chatId, updateChatRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NlSqlChatControllerApi.updateChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NlSqlChatControllerApi - factory interface
 * @export
 */
export const NlSqlChatControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NlSqlChatControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatStream(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<any>> {
            return localVarFp.chatStream(chatId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates new chat
         * @param {CreateChatRequest} createChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createChat(createChatRequest: CreateChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<Chat> {
            return localVarFp.createChat(createChatRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes chat chat
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteChat(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteChat(chatId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChat(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<Chat> {
            return localVarFp.getChat(chatId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} chatId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChatMessages(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ChatMessage>> {
            return localVarFp.listChatMessages(chatId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChats(options?: RawAxiosRequestConfig): AxiosPromise<Array<Chat>> {
            return localVarFp.listChats(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} chatId 
         * @param {SendChatMessageRequest} sendChatMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postChatMessages(chatId: string, sendChatMessageRequest: SendChatMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<ChatMessage> {
            return localVarFp.postChatMessages(chatId, sendChatMessageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates chat
         * @param {string} chatId 
         * @param {UpdateChatRequest} updateChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateChat(chatId: string, updateChatRequest: UpdateChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<Chat> {
            return localVarFp.updateChat(chatId, updateChatRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NlSqlChatControllerApi - interface
 * @export
 * @interface NlSqlChatControllerApi
 */
export interface NlSqlChatControllerApiInterface {
    /**
     * 
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApiInterface
     */
    chatStream(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<any>>;

    /**
     * 
     * @summary Creates new chat
     * @param {CreateChatRequest} createChatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApiInterface
     */
    createChat(createChatRequest: CreateChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<Chat>;

    /**
     * 
     * @summary Deletes chat chat
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApiInterface
     */
    deleteChat(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApiInterface
     */
    getChat(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<Chat>;

    /**
     * 
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApiInterface
     */
    listChatMessages(chatId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ChatMessage>>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApiInterface
     */
    listChats(options?: RawAxiosRequestConfig): AxiosPromise<Array<Chat>>;

    /**
     * 
     * @param {string} chatId 
     * @param {SendChatMessageRequest} sendChatMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApiInterface
     */
    postChatMessages(chatId: string, sendChatMessageRequest: SendChatMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<ChatMessage>;

    /**
     * 
     * @summary Updates chat
     * @param {string} chatId 
     * @param {UpdateChatRequest} updateChatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApiInterface
     */
    updateChat(chatId: string, updateChatRequest: UpdateChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<Chat>;

}

/**
 * NlSqlChatControllerApi - object-oriented interface
 * @export
 * @class NlSqlChatControllerApi
 * @extends {BaseAPI}
 */
export class NlSqlChatControllerApi extends BaseAPI implements NlSqlChatControllerApiInterface {
    /**
     * 
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public chatStream(chatId: string, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).chatStream(chatId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates new chat
     * @param {CreateChatRequest} createChatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public createChat(createChatRequest: CreateChatRequest, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).createChat(createChatRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes chat chat
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public deleteChat(chatId: string, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).deleteChat(chatId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public getChat(chatId: string, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).getChat(chatId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} chatId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public listChatMessages(chatId: string, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).listChatMessages(chatId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public listChats(options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).listChats(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} chatId 
     * @param {SendChatMessageRequest} sendChatMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public postChatMessages(chatId: string, sendChatMessageRequest: SendChatMessageRequest, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).postChatMessages(chatId, sendChatMessageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates chat
     * @param {string} chatId 
     * @param {UpdateChatRequest} updateChatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NlSqlChatControllerApi
     */
    public updateChat(chatId: string, updateChatRequest: UpdateChatRequest, options?: RawAxiosRequestConfig) {
        return NlSqlChatControllerApiFp(this.configuration).updateChat(chatId, updateChatRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



