"""Mill metadata platform HTTP client package."""
from __future__ import annotations

from mill.metadata.bulk import (
    concat_metadata_yaml_documents,
    export_canonical,
    export_canonical_async,
    import_metadata_bundle,
    import_metadata_bundle_async,
    parse_metadata_export_json,
)
from mill.metadata.client import MetadataClient, connect
from mill.metadata.dto import (
    FacetInstanceDto,
    FacetMergeTraceEntryDto,
    FacetMergeTraceResponseDto,
    FacetTypeManifestDto,
    ImportResultDto,
    MetadataAuditRecordDto,
    MetadataEntityDto,
    MetadataScopeDto,
    SearchResultDto,
    TreeNodeDto,
    facet_instance_from_dict,
    facet_merge_trace_entry_from_dict,
    facet_merge_trace_from_dict,
    facet_type_manifest_from_dict,
    import_result_from_dict,
    metadata_audit_record_from_dict,
    metadata_entity_from_dict,
    metadata_scope_from_dict,
    search_result_from_dict,
    tree_node_from_dict,
)

__all__ = [
    "MetadataClient",
    "connect",
    "concat_metadata_yaml_documents",
    "export_canonical",
    "export_canonical_async",
    "import_metadata_bundle",
    "import_metadata_bundle_async",
    "parse_metadata_export_json",
    "FacetInstanceDto",
    "FacetMergeTraceEntryDto",
    "FacetMergeTraceResponseDto",
    "FacetTypeManifestDto",
    "ImportResultDto",
    "MetadataAuditRecordDto",
    "MetadataEntityDto",
    "MetadataScopeDto",
    "SearchResultDto",
    "TreeNodeDto",
    "facet_instance_from_dict",
    "facet_merge_trace_entry_from_dict",
    "facet_merge_trace_from_dict",
    "facet_type_manifest_from_dict",
    "import_result_from_dict",
    "metadata_audit_record_from_dict",
    "metadata_entity_from_dict",
    "metadata_scope_from_dict",
    "search_result_from_dict",
    "tree_node_from_dict",
]
