name: skymill
storage:
  type: adls
  endpoint: https://.blob.core.windows.net
  container: data
  prefix: skymill/avro/
  auth:
    accountKey: ""
table:
  mapping:
    type: regex
    pattern: "(?<table>[^/]+)\\.avro"
readers:
  - type: avro
