name: skymill
storage:
  type: adls
  endpoint: https://millmanualtestsa.blob.core.windows.net
  container: data
  prefix: skymill/parquet/
  auth:
    sasToken: 
table:
  mapping:
    type: regex
    pattern: "(?<table>[^/]+)\\.parquet"
readers:
  - type: parquet
