package db.migration

import org.flywaydb.core.api.migration.BaseJavaMigration
import org.flywaydb.core.api.migration.Context
import java.sql.Connection
import java.sql.Statement

/**
 * Flyway migration replacing string business keys on `metadata_scope` and `metadata_entity`
 * with BIGINT surrogate primary keys (`scope_id`, `entity_id`) and moving URN/FQDN values to
 * `scope_res` / `entity_res`. Dependent tables, facet type definitions, promotion, and audit
 * are updated accordingly. Legacy `metadata_facet_scope` is dropped (data lives in `metadata_facet`).
 *
 * H2 auto-generated FK names vary; [disableRiIfH2] / [enableRiIfH2] toggle referential checks.
 * PostgreSQL uses explicit `DROP CONSTRAINT IF EXISTS` for known default FK names.
 */
@Suppress("ClassName", "unused")
class V9__metadata_surrogate_scope_entity : BaseJavaMigration() {

    override fun migrate(context: Context) {
        val connection = context.connection
        val isH2 = connection.metaData.databaseProductName.equals("H2", ignoreCase = true)
        try {
            if (isH2) disableRiIfH2(connection)
            else dropPostgresForeignKeys(connection)

            exec(connection, "DROP TABLE IF EXISTS metadata_facet_scope")

            exec(connection, "DROP INDEX IF EXISTS idx_metadata_facet_entity")
            exec(connection, "DROP INDEX IF EXISTS idx_metadata_facet_scope")
            exec(connection, "DROP INDEX IF EXISTS idx_moa_entity")
            exec(connection, "DROP INDEX IF EXISTS idx_mp_entity")

            // --- Surrogate columns on scope & entity (keep legacy varchar PK columns until end) ---
            exec(connection, """
                ALTER TABLE metadata_scope ADD COLUMN IF NOT EXISTS scope_sid BIGINT GENERATED BY DEFAULT AS IDENTITY
            """.trimIndent())
            exec(connection, "ALTER TABLE metadata_scope ADD COLUMN IF NOT EXISTS scope_res VARCHAR(255)")
            exec(connection, "UPDATE metadata_scope SET scope_res = scope_id WHERE scope_res IS NULL")
            exec(connection, "ALTER TABLE metadata_scope ALTER COLUMN scope_res SET NOT NULL")

            exec(connection, """
                ALTER TABLE metadata_entity ADD COLUMN IF NOT EXISTS entity_sid BIGINT GENERATED BY DEFAULT AS IDENTITY
            """.trimIndent())
            exec(connection, "ALTER TABLE metadata_entity ADD COLUMN IF NOT EXISTS entity_res VARCHAR(255)")
            exec(connection, "UPDATE metadata_entity SET entity_res = entity_id WHERE entity_res IS NULL")
            exec(connection, "ALTER TABLE metadata_entity ALTER COLUMN entity_res SET NOT NULL")

            // --- metadata_facet: switch to BIGINT FK placeholders ---
            exec(connection, "ALTER TABLE metadata_facet ADD COLUMN IF NOT EXISTS entity_fk BIGINT")
            exec(connection, "ALTER TABLE metadata_facet ADD COLUMN IF NOT EXISTS scope_fk BIGINT")
            exec(connection, """
                UPDATE metadata_facet mf
                SET entity_fk = (SELECT e.entity_sid FROM metadata_entity e WHERE e.entity_id = mf.entity_id),
                    scope_fk = (SELECT s.scope_sid FROM metadata_scope s WHERE s.scope_id = mf.scope_id)
            """.trimIndent())
            exec(connection, "ALTER TABLE metadata_facet ALTER COLUMN entity_fk SET NOT NULL")
            exec(connection, "ALTER TABLE metadata_facet ALTER COLUMN scope_fk SET NOT NULL")
            exec(connection, "ALTER TABLE metadata_facet DROP COLUMN entity_id")
            exec(connection, "ALTER TABLE metadata_facet DROP COLUMN scope_id")
            exec(connection, "ALTER TABLE metadata_facet RENAME COLUMN entity_fk TO entity_id")
            exec(connection, "ALTER TABLE metadata_facet RENAME COLUMN scope_fk TO scope_id")

            // --- metadata_operation_audit (no FK): entity_id becomes BIGINT + entity_res ---
            exec(connection, "ALTER TABLE metadata_operation_audit ADD COLUMN IF NOT EXISTS moa_entity_ref BIGINT")
            exec(connection, "ALTER TABLE metadata_operation_audit ADD COLUMN IF NOT EXISTS moa_entity_res VARCHAR(255)")
            exec(connection, """
                UPDATE metadata_operation_audit moa
                SET moa_entity_res = moa.entity_id,
                    moa_entity_ref = (SELECT e.entity_sid FROM metadata_entity e WHERE e.entity_id = moa.entity_id)
                WHERE moa.entity_id IS NOT NULL
            """.trimIndent())
            exec(connection, "ALTER TABLE metadata_operation_audit DROP COLUMN entity_id")
            exec(connection, "ALTER TABLE metadata_operation_audit RENAME COLUMN moa_entity_ref TO entity_id")
            exec(connection, "ALTER TABLE metadata_operation_audit RENAME COLUMN moa_entity_res TO entity_res")
            exec(connection, "ALTER TABLE metadata_operation_audit RENAME COLUMN scope_key TO scope_res")
            exec(connection, "ALTER TABLE metadata_operation_audit RENAME COLUMN facet_type TO facet_type_res")

            // --- metadata_promotion ---
            exec(connection, "ALTER TABLE metadata_promotion RENAME COLUMN facet_type TO facet_type_res")
            exec(connection, "ALTER TABLE metadata_promotion ADD COLUMN IF NOT EXISTS mp_entity_fk BIGINT")
            exec(connection, "ALTER TABLE metadata_promotion ADD COLUMN IF NOT EXISTS mp_entity_res VARCHAR(255)")
            exec(connection, "ALTER TABLE metadata_promotion ADD COLUMN IF NOT EXISTS mp_src_scope_fk BIGINT")
            exec(connection, "ALTER TABLE metadata_promotion ADD COLUMN IF NOT EXISTS mp_src_scope_res VARCHAR(255)")
            exec(connection, "ALTER TABLE metadata_promotion ADD COLUMN IF NOT EXISTS mp_tgt_scope_fk BIGINT")
            exec(connection, "ALTER TABLE metadata_promotion ADD COLUMN IF NOT EXISTS mp_tgt_scope_res VARCHAR(255)")
            exec(connection, """
                UPDATE metadata_promotion p
                SET mp_entity_res = p.entity_id,
                    mp_entity_fk = (SELECT e.entity_sid FROM metadata_entity e WHERE e.entity_id = p.entity_id),
                    mp_src_scope_res = p.source_scope_id,
                    mp_src_scope_fk = (SELECT s.scope_sid FROM metadata_scope s WHERE s.scope_id = p.source_scope_id),
                    mp_tgt_scope_res = p.target_scope_id,
                    mp_tgt_scope_fk = (SELECT s.scope_sid FROM metadata_scope s WHERE s.scope_id = p.target_scope_id)
            """.trimIndent())
            exec(connection, "ALTER TABLE metadata_promotion ALTER COLUMN mp_entity_fk SET NOT NULL")
            exec(connection, "ALTER TABLE metadata_promotion ALTER COLUMN mp_src_scope_fk SET NOT NULL")
            exec(connection, "ALTER TABLE metadata_promotion ALTER COLUMN mp_tgt_scope_fk SET NOT NULL")
            exec(connection, "ALTER TABLE metadata_promotion DROP COLUMN entity_id")
            exec(connection, "ALTER TABLE metadata_promotion DROP COLUMN source_scope_id")
            exec(connection, "ALTER TABLE metadata_promotion DROP COLUMN target_scope_id")
            exec(connection, "ALTER TABLE metadata_promotion RENAME COLUMN mp_entity_fk TO entity_id")
            exec(connection, "ALTER TABLE metadata_promotion RENAME COLUMN mp_entity_res TO entity_res")
            exec(connection, "ALTER TABLE metadata_promotion RENAME COLUMN mp_src_scope_fk TO source_scope_id")
            exec(connection, "ALTER TABLE metadata_promotion RENAME COLUMN mp_src_scope_res TO source_scope_res")
            exec(connection, "ALTER TABLE metadata_promotion RENAME COLUMN mp_tgt_scope_fk TO target_scope_id")
            exec(connection, "ALTER TABLE metadata_promotion RENAME COLUMN mp_tgt_scope_res TO target_scope_res")

            // --- Facet type def: add surrogate + type_res; inst switches FK before def PK changes ---
            exec(connection, """
                ALTER TABLE metadata_facet_type_def ADD COLUMN IF NOT EXISTS facet_type_def_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
            """.trimIndent())
            exec(connection, "ALTER TABLE metadata_facet_type_def ADD COLUMN IF NOT EXISTS type_res VARCHAR(255)")
            exec(connection, "UPDATE metadata_facet_type_def SET type_res = type_key WHERE type_res IS NULL")
            exec(connection, "ALTER TABLE metadata_facet_type_def ALTER COLUMN type_res SET NOT NULL")

            exec(connection, "ALTER TABLE metadata_facet_type ADD COLUMN IF NOT EXISTS facet_type_def_fk BIGINT")
            exec(connection, """
                UPDATE metadata_facet_type ft
                SET facet_type_def_fk = (
                    SELECT d.facet_type_def_id FROM metadata_facet_type_def d WHERE d.type_key = ft.facet_type_def_key
                )
                WHERE ft.facet_type_def_key IS NOT NULL
            """.trimIndent())

            dropFkMetadataFacetTypeToTypeDef(connection, isH2)
            exec(connection, "ALTER TABLE metadata_facet_type DROP COLUMN facet_type_def_key")
            exec(connection, "ALTER TABLE metadata_facet_type RENAME COLUMN facet_type_def_fk TO facet_type_def_id")
            exec(connection, "ALTER TABLE metadata_facet_type RENAME COLUMN type_key TO type_res")

            dropTablePrimaryKey(connection, isH2, "metadata_facet_type_def")
            exec(connection, "ALTER TABLE metadata_facet_type_def DROP COLUMN type_key")
            exec(connection, "ALTER TABLE metadata_facet_type_def ADD PRIMARY KEY (facet_type_def_id)")
            exec(connection, "CREATE UNIQUE INDEX IF NOT EXISTS uq_metadata_facet_type_def_type_res ON metadata_facet_type_def(type_res)")

            exec(connection, """
                ALTER TABLE metadata_facet_type
                ADD CONSTRAINT fst_mft_def_fk FOREIGN KEY (facet_type_def_id)
                REFERENCES metadata_facet_type_def(facet_type_def_id)
            """.trimIndent())

            // --- Finalize scope PK ---
            dropTablePrimaryKey(connection, isH2, "metadata_scope")
            exec(connection, "ALTER TABLE metadata_scope DROP COLUMN scope_id")
            exec(connection, "ALTER TABLE metadata_scope RENAME COLUMN scope_sid TO scope_id")
            exec(connection, "ALTER TABLE metadata_scope ADD PRIMARY KEY (scope_id)")
            exec(connection, "CREATE UNIQUE INDEX IF NOT EXISTS uq_metadata_scope_scope_res ON metadata_scope(scope_res)")

            // --- Finalize entity PK ---
            dropTablePrimaryKey(connection, isH2, "metadata_entity")
            exec(connection, "ALTER TABLE metadata_entity DROP COLUMN entity_id")
            exec(connection, "ALTER TABLE metadata_entity RENAME COLUMN entity_sid TO entity_id")
            exec(connection, "ALTER TABLE metadata_entity ADD PRIMARY KEY (entity_id)")
            exec(connection, "CREATE UNIQUE INDEX IF NOT EXISTS uq_metadata_entity_entity_res ON metadata_entity(entity_res)")

            // --- Re-create child FKs ---
            exec(connection, """
                ALTER TABLE metadata_facet
                ADD CONSTRAINT fk_metadata_facet_entity FOREIGN KEY (entity_id) REFERENCES metadata_entity(entity_id) ON DELETE CASCADE
            """.trimIndent())
            exec(connection, """
                ALTER TABLE metadata_facet
                ADD CONSTRAINT fk_metadata_facet_scope FOREIGN KEY (scope_id) REFERENCES metadata_scope(scope_id) ON DELETE CASCADE
            """.trimIndent())
            exec(connection, """
                ALTER TABLE metadata_promotion
                ADD CONSTRAINT fk_mp_entity FOREIGN KEY (entity_id) REFERENCES metadata_entity(entity_id) ON DELETE CASCADE
            """.trimIndent())
            exec(connection, """
                ALTER TABLE metadata_promotion
                ADD CONSTRAINT fk_mp_src_scope FOREIGN KEY (source_scope_id) REFERENCES metadata_scope(scope_id)
            """.trimIndent())
            exec(connection, """
                ALTER TABLE metadata_promotion
                ADD CONSTRAINT fk_mp_tgt_scope FOREIGN KEY (target_scope_id) REFERENCES metadata_scope(scope_id)
            """.trimIndent())

            exec(connection, "CREATE INDEX IF NOT EXISTS idx_metadata_facet_entity ON metadata_facet(entity_id)")
            exec(connection, "CREATE INDEX IF NOT EXISTS idx_metadata_facet_scope ON metadata_facet(scope_id)")
            exec(connection, "CREATE INDEX IF NOT EXISTS idx_moa_entity ON metadata_operation_audit(entity_id)")
            exec(connection, "CREATE INDEX IF NOT EXISTS idx_mp_entity ON metadata_promotion(entity_id, facet_type_res)")
        } finally {
            if (isH2) enableRiIfH2(connection)
        }
    }

    private fun disableRiIfH2(connection: Connection) {
        connection.createStatement().use { st -> st.execute("SET REFERENTIAL_INTEGRITY FALSE") }
    }

    private fun enableRiIfH2(connection: Connection) {
        connection.createStatement().use { st -> st.execute("SET REFERENTIAL_INTEGRITY TRUE") }
    }

    private fun dropPostgresForeignKeys(connection: Connection) {
        val stmts = listOf(
            "ALTER TABLE metadata_promotion DROP CONSTRAINT IF EXISTS metadata_promotion_entity_id_fkey",
            "ALTER TABLE metadata_promotion DROP CONSTRAINT IF EXISTS metadata_promotion_source_scope_id_fkey",
            "ALTER TABLE metadata_promotion DROP CONSTRAINT IF EXISTS metadata_promotion_target_scope_id_fkey",
            "ALTER TABLE metadata_facet DROP CONSTRAINT IF EXISTS metadata_facet_entity_id_fkey",
            "ALTER TABLE metadata_facet DROP CONSTRAINT IF EXISTS metadata_facet_scope_id_fkey",
        )
        for (sql in stmts) {
            exec(connection, sql)
        }
    }

    /**
     * Drops FK from `metadata_facet_type.facet_type_def_key` to `metadata_facet_type_def` (required before
     * replacing the def PK). PostgreSQL: fixed name; H2: JDBC [getImportedKeys] on the parent def table.
     */
    private fun dropFkMetadataFacetTypeToTypeDef(connection: Connection, isH2: Boolean) {
        if (!isH2) {
            exec(connection, "ALTER TABLE metadata_facet_type DROP CONSTRAINT IF EXISTS metadata_facet_type_facet_type_def_key_fkey")
            return
        }
        connection.metaData.getImportedKeys(null, null, "METADATA_FACET_TYPE_DEF").use { rs ->
            while (rs.next()) {
                val fkTable = rs.getString("FKTABLE_NAME") ?: continue
                val fkName = rs.getString("FK_NAME") ?: continue
                if (fkTable.equals("metadata_facet_type", ignoreCase = true)) {
                    val q = fkName.uppercase().replace("\"", "\"\"")
                    exec(connection, "ALTER TABLE metadata_facet_type DROP CONSTRAINT \"$q\"")
                    return
                }
            }
        }
    }

    private fun exec(connection: Connection, sql: String) {
        connection.createStatement().use { st: Statement ->
            st.execute(sql)
        }
    }

    /**
     * Drops the table's primary key by resolving the real constraint name from INFORMATION_SCHEMA.
     * PostgreSQL keeps the historical `{old_table}_pkey` name after `RENAME TABLE` (e.g. `metadata_facet_type_pkey`),
     * so hard-coding `metadata_facet_type_def_pkey` fails on upgraded databases.
     */
    private fun dropTablePrimaryKey(connection: Connection, isH2: Boolean, table: String) {
        val pkName = fetchPrimaryKeyConstraintName(connection, table)
            ?: throw IllegalStateException("No primary key found for table $table")
        if (isH2) {
            // INFORMATION_SCHEMA may return lowercased names; H2's catalog uses uppercase auto-names.
            val h2Name = pkName.uppercase().replace("\"", "\"\"")
            exec(connection, "ALTER TABLE $table DROP CONSTRAINT \"$h2Name\"")
        } else {
            val q = pkName.replace("\"", "\"\"")
            exec(connection, "ALTER TABLE $table DROP CONSTRAINT \"$q\"")
        }
    }

    /** Resolves PRIMARY KEY constraint name (H2 auto-names; PostgreSQL may not rename PK with the table). */
    private fun fetchPrimaryKeyConstraintName(connection: Connection, table: String): String? {
        val sql = """
            SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
            WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
              AND UPPER(TABLE_NAME) = UPPER(?)
              AND TABLE_SCHEMA NOT IN ('information_schema', 'pg_catalog')
        """.trimIndent()
        connection.prepareStatement(sql).use { ps ->
            ps.setString(1, table)
            ps.executeQuery().use { rs ->
                return if (rs.next()) rs.getString(1) else null
            }
        }
    }
}
