version: '2'
services:
  zookeeper:
    image: zookeeper
  postgres-test:
    image: qpointz/postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
