grpc:
  server:
    port: ${mill.services.grpc.port}
    address: ${mill.services.grpc.address}

mill:
  services:
    meta:
      enable: true
    grpc:
      port: 9099
      enable: true
      address: '*'