grpc:
  server:
    security:
      enabled: true
      certificate-chain: file:/config/ssl/server.crt
      private-key: file:/config/ssl/server.key

mill:
  backend:
    security:                        
      providers:
        - type: file
          path: /config/passwd.yml
        - type: jwt
          issuer-uri: "${MILL_OAUTH_ISSUER_URL}"
