include:
  - local : /.gitlab/vars.yml
  - local : /.gitlab/jobs.yml

workflow:
  rules:
      - when : always

stages:
  - init

init:build-graalvm-ci-image:
  stage: init
  extends: .docker-build-job
  script:
      - >
        /kaniko/executor
        --context "${CI_PROJECT_DIR}/etc/docker/ci-graalvm" 
        --destination "${CI_IMAGE_GRAALVM}"
        --cache=true

init:build-gradle-ci-image:
  stage: init
  extends: .docker-build-job
  needs:
    - job: init:build-graalvm-ci-image
      artifacts: false
  script:
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/etc/docker/ci-gradle"
      --destination "${CI_IMAGE_GRADLE}"
      --build-arg "BASE_IMAGE=${CI_IMAGE_GRAALVM}"
      --cache=true


init:build-sbt-ci-image:
  stage: init
  extends: .docker-build-job
  needs:
    - job: init:build-graalvm-ci-image
      artifacts: false
  script:
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/etc/docker/ci-sbt"
      --destination "${CI_IMAGE_SBT}"
      --build-arg "BASE_IMAGE=${CI_IMAGE_GRAALVM}"
      --cache=true

# init:build-npm-ci-image:
#   stage: init
#   extends: .docker-build-job
#   script:
#     - >
#       /kaniko/executor
#       --context "${CI_PROJECT_DIR}/etc/docker/ci-npm"
#       --destination "${CI_IMAGES_NPM}"
#       --cache=true