include:
  - local : /.gitlab/vars.yml
  - local : /.gitlab/jobs.yml

workflow:
  rules:
      - when : always

stages:
  - init

init:build-base-ci-image:
  stage: init
  extends: .docker-build-job
  script:
      - >
        /kaniko/executor
        --context "${CI_PROJECT_DIR}/etc/docker/base-ci" 
        --destination "${CI_IMAGE_BASE}"
        --cache=true

init:build-graalvm-ci-image:
  stage: init
  extends: .docker-build-job
  needs:
    - job: init:build-base-ci-image
      artifacts: false  
  script:
      - >
        /kaniko/executor
        --context "${CI_PROJECT_DIR}/etc/docker/graalvm-ci" 
        --destination "${CI_IMAGE_GRAALVM}"
        --build-arg "BASE_IMAGE=${CI_IMAGE_BASE}"
        --cache=true

init:build-gradle-ci-image:
  stage: init
  extends: .docker-build-job
  needs:
    - job: init:build-graalvm-ci-image
      artifacts: false
  script:
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/etc/docker/gradle-ci"
      --destination "${CI_IMAGE_GRADLE}"
      --build-arg "BASE_IMAGE=${CI_IMAGE_GRAALVM}"
      --cache=true


init:build-sbt-ci-image:
  stage: init
  extends: .docker-build-job
  needs:
    - job: init:build-graalvm-ci-image
      artifacts: false
  script:
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/etc/docker/sbt-ci"
      --destination "${CI_IMAGE_SBT}"
      --build-arg "BASE_IMAGE=${CI_IMAGE_GRAALVM}"
      --cache=true

init:build-npm-ci-image:
  stage: init
  extends: .docker-build-job
  script:
      - >
        /kaniko/executor
        --context "${CI_PROJECT_DIR}/etc/docker/npm-ci" 
        --destination "${CI_IMAGE_NPM}"        
        --cache=true

init:build-semantic-release-image:
  stage: init
  extends: .docker-build-job
  script:
      - >
        /kaniko/executor
        --context "${CI_PROJECT_DIR}/etc/docker/sem-release-ci" 
        --destination "${CI_IMAGE_SEM_RELEASE}"        
        --build-arg "BASE_IMAGE=${CI_IMAGE_NPM}"
        --cache=true        

pages:build-sphinx-ci-image:
  stage: init
  extends: .docker-build-job
  script:
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/etc/docker/sphinx-ci" 
      --build-arg "BASE_IMAGE=${CI_IMAGE_PYTHON}"
      --destination "${CI_IMAGE_SPHINX}"
      --cache=true               
