include:
  - local : /.gitlab/vars.yml
  - local : /.gitlab/jobs.yml

workflow:
  rules:
      - when : always

stages:
  - init

init:build-base-ci-image:
  stage: init
  extends: .docker-build-job
  script:
      - >
        /kaniko/executor
        --context "${CI_PROJECT_DIR}/etc/docker/base-ci" 
        --destination "${CI_IMAGE_BASE}"
        --cache=true


init:build-semantic-release-image:
  stage: init
  extends: .docker-build-job
  script:
      - >
        /kaniko/executor
        --context "${CI_PROJECT_DIR}/etc/docker/sem-release-ci" 
        --destination "${CI_IMAGE_SEM_RELEASE}"        
        --build-arg "BASE_IMAGE=${CI_IMAGE_NPM}"
        --cache=true        

init:build-minica-image:
  stage: init
  extends: .docker-build-job
  script:
      - >
        /kaniko/executor
        --context "${CI_PROJECT_DIR}/etc/docker/minica" 
        --destination "${CI_IMAGE_MINICA}"
        --cache=true               
