stages:  
  - integration

workflow:
  rules:
    - when: always

ai:integration:
  stage: integration
  trigger:
    strategy: mirror
    include:    
      - local: ai/.gitlab/pipelines/integration.yml        

clients:integration:
  stage: integration
  trigger:
    strategy: mirror
    include:    
      - local: clients/.gitlab/pipelines/integration.yml