stages:
  - init
  - integration

workflow:
  rules:
    - when: always

init:
  stage: init
  script:
    - echo "Integration build"

integration:
  stage: integration
  script:
    - echo "Integration build"