include:
  - local: /.gitlab/common/common.yml

workflow:
  rules:
    - when: always

stages:
  - init
  - integration

init-integration:
  stage: init
  script:
    - echo "Init integration"
    - echo "CI_PIPELINE_SOURCE=${CI_PIPELINE_SOURCE}"
    - echo "CI_OPEN_MERGE_REQUESTS=${CI_OPEN_MERGE_REQUESTS}"
    - echo "CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED=${CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED}"
    - echo "CI_COMMIT_REF_PROTECTED=${CI_COMMIT_REF_PROTECTED}"
    - echo "CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SLUG}"
    - echo "CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}"
    - echo "CI_COMMIT_REF_MESSAGE=${CI_COMMIT_REF_MESSAGE}"
    - echo "CI_COMMIT_REF_TIMESTAMP=${CI_COMMIT_REF_TIMESTAMP}"
    - echo "CI_COMMIT_REF_SHA=${CI_COMMIT_REF_SHA}"
    - echo "CI_COMMIT_REF_MESSAGE=${CI_COMMIT_REF_MESSAGE}"
    - echo "CI_COMMIT_REF_TIMESTAMP=${CI_COMMIT_REF_TIMESTAMP}"
    - echo "CI_COMMIT_REF_AUTHOR=${CI_COMMIT_REF_AUTHOR}"
    - echo "CI_COMMIT_REF_AUTHOR_EMAIL=${CI_COMMIT_REF_AUTHOR_EMAIL}"


ai:integration:
  stage: integration
  extends:
    - .gradle-job
    - .integration-job
  allow_failure: true
  script:
    - !reference [ .global-vars, before_script ]
    - export REGRESSION_VERSION_TAG=${QP_VERSION}
    - echo "REGRESSION_VERSION_TAG=${REGRESSION_VERSION_TAG}"
    - ./gradlew --no-daemon --continue --console plain :ai:testIT
  artifacts:
    when: always
    expire_in: "5 days"
    paths:
      - ${CI_PROJECT_DIR}/ai/mill-ai-v1-core/build/reports/scenarios/*.json

#ai:publish-regression:
#  stage: integration
#  extends:
#    - .integration-job
#  needs:
#    - job: ai:integration
#      artifacts: true
#  script:
#    - !reference [ .global-vars, before_script ]
#    - export REGRESSION_VERSION_TAG=${QP_VERSION}
#    - mkdir -p /out/regression/reports/ai/${REGRESSION_VERSION_TAG}
#    - rm -Rf /out/regression/reports/ai/${REGRESSION_VERSION_TAG}/ 2> /dev/null
#    - mkdir -p /out/regression/reports/ai/${REGRESSION_VERSION_TAG}
#    - ls -l ${CI_PROJECT_DIR}/ai/mill-ai-v1-core/build/reports/scenarios/*.*
#    - cp -Rf ${CI_PROJECT_DIR}/ai/mill-ai-v1-core/build/reports/scenarios/*.* /out/regression/reports/ai/${REGRESSION_VERSION_TAG}/
#    - ls -lacr /out/regression/reports/
#    - cd /out/regression/
#    - tar czfv /out/regression/pack-${REGRESSION_VERSION_TAG}-$(date +%Y%m%d-%H%M%S).tar.gz ./reports
#    - cp /out/regression/pack-${REGRESSION_VERSION_TAG}-$(date +%Y%m%d-%H%M%S).tar.gz ${CI_PROJECT_DIR}/ai/mill-ai-v1-core/build/reports/scenarios/
#  artifacts:
#    expire_in: "5 days"
#    paths:
#      - ${CI_PROJECT_DIR}/ai/mill-ai-v1-core/build/reports/scenarios/pack-*.tar.gz

.mill-py-integration-template:
  stage: integration
  extends:
    - .python-job
    - .integration-job
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:${PY_VER}-slim
  allow_failure: true
  variables:
    CI_DEBUG_SERVICES: "false"
    # Runtime
    PY_VER: "3.10"
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PIP_ROOT_USER_ACTION: "ignore"
    # Integration connection configuration consumed by tests/integration/conftest.py
    MILL_IT_HOST: "mill-it"
    MILL_IT_PORT: "9090"
    MILL_IT_PROTOCOL: "grpc"         # grpc | http-json | http-protobuf
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_TLS_CA: ""
    MILL_IT_TLS_CERT: ""
    MILL_IT_TLS_KEY: ""
    MILL_IT_AUTH: "none"             # none | basic | bearer
    MILL_IT_USERNAME: "reader"
    MILL_IT_PASSWORD: "reader"
    MILL_IT_TOKEN: ""
    MILL_IT_SCHEMA: "skymill"

    # Optional custom pytest selector
    MILL_IT_PYTEST_PATH: "tests/integration/"
  services:
    - name: ${CI_REGISTRY_IMAGE}/mill-service-samples:${CI_COMMIT_REF_SLUG}
      alias: mill-it
      command: [""]
      entrypoint: ["./bin/mill-service"]
      pull_policy: [always]
  script:
    - cd ${CI_PROJECT_DIR}/clients/mill-py
    - echo "Waiting 30s for integration service startup..."
    - sleep 30
    - |
      echo "Integration params:"
      echo "  MILL_IT_PROTOCOL=${MILL_IT_PROTOCOL}"
      echo "  MILL_IT_HOST=${MILL_IT_HOST}"
      echo "  MILL_IT_PORT=${MILL_IT_PORT}"
      echo "  MILL_IT_BASE_PATH=${MILL_IT_BASE_PATH}"
      echo "  MILL_IT_AUTH=${MILL_IT_AUTH}"
      echo "  MILL_IT_TLS=${MILL_IT_TLS}"
      echo "  MILL_IT_SCHEMA=${MILL_IT_SCHEMA}"
    - |
      if [ "${MILL_IT_PROTOCOL}" = "http-json" ] || [ "${MILL_IT_PROTOCOL}" = "http-protobuf" ] || [ "${MILL_IT_PROTOCOL}" = "http" ]; then
        echo "HTTP route diagnostics (non-fatal):"
        curl -i -X POST "http://${MILL_IT_HOST}:${MILL_IT_PORT}${MILL_IT_BASE_PATH}/Handshake" \
          -H "Content-Type: application/json" \
          -d '{}' || true
        curl -i -X POST "http://${MILL_IT_HOST}:${MILL_IT_PORT}/api/Handshake" \
          -H "Content-Type: application/json" \
          -d '{}' || true
      fi
    - python --version
    - pip install poetry
    - poetry install --all-extras
    - |
      poetry run pytest \
        -s \
        -m integration \
        --junitxml=build/test-results/integration-results.xml \
        ${MILL_IT_PYTEST_PATH}
  artifacts:
    when: always
    expire_in: "5 days"
    reports:
      junit: ${CI_PROJECT_DIR}/clients/mill-py/build/test-results/*.xml
    paths:
      - ${CI_PROJECT_DIR}/clients/mill-py/build/test-results/*.xml


clients:mill-py:integration:grpc-noauth:3.10:
  extends:
    - .mill-py-integration-template
  variables:
    PY_VER: "3.10"
    MILL_IT_HOST: "mill-it"
    MILL_IT_PORT: "9090"
    MILL_IT_PROTOCOL: "grpc"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"


clients:mill-py:integration:grpc-noauth:3.11:
  extends:
    - .mill-py-integration-template
  variables:
    PY_VER: "3.11"
    MILL_IT_HOST: "mill-it"
    MILL_IT_PORT: "9090"
    MILL_IT_PROTOCOL: "grpc"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"

clients:mill-py:integration:grpc-noauth:3.12:
  extends:
    - .mill-py-integration-template
  variables:
    PY_VER: "3.12"
    MILL_IT_HOST: "mill-it"
    MILL_IT_PORT: "9090"
    MILL_IT_PROTOCOL: "grpc"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"


clients:mill-py:integration:http-json-noauth:3.10:
  extends:
    - .mill-py-integration-template
  variables:
    PY_VER: "3.10"
    MILL_IT_HOST: "mill-it"
    MILL_IT_PORT: "8080"
    MILL_IT_PROTOCOL: "http-json"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"


clients:mill-py:integration:http-json-noauth:3.11:
  extends:
    - .mill-py-integration-template
  variables:
    PY_VER: "3.11"
    MILL_IT_HOST: "mill-it"
    MILL_IT_PORT: "8080"
    MILL_IT_PROTOCOL: "http-json"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"

clients:mill-py:integration:http-json-noauth:3.12:
  extends:
    - .mill-py-integration-template
  variables:
    PY_VER: "3.12"
    MILL_IT_HOST: "mill-it"
    MILL_IT_PORT: "8080"
    MILL_IT_PROTOCOL: "http-json"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"

clients:mill-py:integration:http-protobuf-noauth:3.10:
  extends:
    - .mill-py-integration-template
  variables:
    PY_VER: "3.10"
    MILL_IT_HOST: "mill-it"
    MILL_IT_PORT: "8080"
    MILL_IT_PROTOCOL: "http-protobuf"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"


clients:mill-py:integration:http-protobuf-noauth:3.11:
  extends:
    - .mill-py-integration-template
  variables:
    PY_VER: "3.11"
    MILL_IT_HOST: "mill-it"
    MILL_IT_PORT: "8080"
    MILL_IT_PROTOCOL: "http-protobuf"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"

clients:mill-py:integration:http-protobuf-noauth:3.12:
  extends:
    - .mill-py-integration-template
  variables:
    PY_VER: "3.12"
    MILL_IT_HOST: "mill-it"
    MILL_IT_PORT: "8080"
    MILL_IT_PROTOCOL: "http-protobuf"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"


.mill-jdbc-integration-template:
  stage: integration
  extends:
    - .gradle-job
    - .integration-job
  allow_failure: true
  variables:
    # Integration connection configuration consumed by JDBC testIT profile
    MILL_IT_HOST: "mill"
    MILL_IT_PORT: "9090"
    MILL_IT_PROTOCOL: "grpc"         # grpc | http-json | http-protobuf | http
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_TLS_CA: ""
    MILL_IT_TLS_CERT: ""
    MILL_IT_TLS_KEY: ""
    MILL_IT_AUTH: "none"             # none | basic | bearer
    MILL_IT_USERNAME: "reader"
    MILL_IT_PASSWORD: "reader"
    MILL_IT_TOKEN: ""
    MILL_IT_SCHEMA: "skymill"
  services:
    - name: ${CI_REGISTRY_IMAGE}/mill-service-samples:${CI_COMMIT_REF_SLUG}
      alias: mill
      pull_policy: [always]
      command: [""]
      entrypoint: ["./bin/mill-service"]
  script:
    - echo "Waiting 30s for integration service startup..."
    - sleep 30
    - |
      echo "Integration params:"
      echo "  MILL_IT_PROTOCOL=${MILL_IT_PROTOCOL}"
      echo "  MILL_IT_HOST=${MILL_IT_HOST}"
      echo "  MILL_IT_PORT=${MILL_IT_PORT}"
      echo "  MILL_IT_BASE_PATH=${MILL_IT_BASE_PATH}"
      echo "  MILL_IT_AUTH=${MILL_IT_AUTH}"
      echo "  MILL_IT_TLS=${MILL_IT_TLS}"
      echo "  MILL_IT_SCHEMA=${MILL_IT_SCHEMA}"
    - |
      if [ "${MILL_IT_PROTOCOL}" = "http-json" ] || [ "${MILL_IT_PROTOCOL}" = "http-protobuf" ] || [ "${MILL_IT_PROTOCOL}" = "http" ]; then
        echo "HTTP route diagnostics (non-fatal):"
        curl -i -X POST "http://${MILL_IT_HOST}:${MILL_IT_PORT}${MILL_IT_BASE_PATH}/Handshake" \
          -H "Content-Type: application/json" \
          -d '{}' || true
        curl -i -X POST "http://${MILL_IT_HOST}:${MILL_IT_PORT}/api/Handshake" \
          -H "Content-Type: application/json" \
          -d '{}' || true
      fi
    - ./gradlew --no-daemon --console plain --info :clients:mill-jdbc-driver:testIT
  artifacts:
    when: always
    expire_in: "5 days"
    reports:
      junit: ${CI_PROJECT_DIR}/clients/mill-jdbc-driver/build/test-results/testIT/*.xml
    paths:
      - ${CI_PROJECT_DIR}/clients/mill-jdbc-driver/build/reports/tests/testIT/**
      - ${CI_PROJECT_DIR}/clients/mill-jdbc-driver/build/test-results/testIT/*.xml


clients:mill-jdbc:integration:grpc-noauth:
  extends:
    - .mill-jdbc-integration-template
  variables:
    MILL_IT_HOST: "mill"
    MILL_IT_PORT: "9090"
    MILL_IT_PROTOCOL: "grpc"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"


clients:mill-jdbc:integration:http-json-noauth:
  extends:
    - .mill-jdbc-integration-template
  variables:
    MILL_IT_HOST: "mill"
    MILL_IT_PORT: "8080"
    MILL_IT_PROTOCOL: "http-json"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"


clients:mill-jdbc:integration:http-protobuf-noauth:
  extends:
    - .mill-jdbc-integration-template
  variables:
    MILL_IT_HOST: "mill"
    MILL_IT_PORT: "8080"
    MILL_IT_PROTOCOL: "http-protobuf"
    MILL_IT_BASE_PATH: "/services/jet"
    MILL_IT_TLS: "false"
    MILL_IT_AUTH: "none"
    MILL_IT_SCHEMA: "skymill"