spec:
  inputs:
    package-local-only: 
      default: "true"
      description: "Package local only"
      options:  
        - "true"
        - "false"
---
stages:  
  - package

workflow:
  rules:
    - when: always

apps:package:
  stage: package
  trigger:
    strategy: mirror
    include:    
      - local: apps/.gitlab/pipelines/package.yml    
        inputs:
          package-local-only: $[[ inputs.package-local-only ]]

package:
  stage: package
  script:
    - echo "Publish run"
    - echo $[[ inputs.package-local-only ]]