stages:
  - init
  - package
  - publish

workflow:
  rules:
    - when: always  

include:
  - local : /.gitlab/.vars.yml

init:
  stage: init
  script:
    - echo "Publish init"

apps:publish:
  stage: package
  trigger:
    strategy: mirror
    include:    
      - local: apps/.gitlab/pipelines/package.yml    
        inputs:
          package-local-only: false

publish-docs:
  stage: package
  trigger:    
    strategy: mirror
    include:
      - local: docs/.gitlab-ci.yml

semantic-release:
  image: ${IMAGE_SEM_RELEASE}
  stage: publish
  variables:
    GIT_STRATEGY: clone      
    GL_TOKEN: ${CI_PUSH_TOKEN}
    GL_URL: "https://gitlab.qpointz.io"
    GIT_DEPTH: 0
  only:
    - main 
    - rc
  script:
    - export GITLAB_TOKEN=${CI_PUSH_TOKEN}
    - npx semantic-release --ci --debug      