apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: qpointz
spec:
  selector:
    app: localstack
  type: NodePort
  ports:
    - port: 4566
      name: edge
      nodePort: 30010
    - port: 8080
      name: dash
      nodePort: 30011

---

apiVersion: v1
kind: Service
metadata:
  name: hadoop
  namespace: qpointz
spec:
  selector:
    app: hadoop
  type: NodePort
  ports:
    #zookeeper
    - port: 22010
      name: zookeeper
      nodePort: 30100

    #hdfs
    - port: 20112
      name: hdfs-namenode
      nodePort: 30111
    - port: 50070
      name: hdfs-namenode-http
      nodePort: 30112
    - port: 50010
      name: hdfs-datanode
      nodePort: 30113
    - port: 50075
      name: hdfs-datanode-http
      nodePort: 30114
    - port: 50020
      name: hdfs-datanode-ipc
      nodePort: 30115

    #kafka
    - port: 20111
      name: kafka
      nodePort: 30120

    #hbase
    - port: 2511
      name: hbase-master
      nodePort: 30130
    - port: 28000
      name: hbase-rest
      nodePort: 30131
    - port: 28080
      name: hbase-rest-info
      nodePort: 30132
---
apiVersion: v1
kind: Service
metadata:
  name: apache-drill
  namespace: qpointz
spec:
  selector:
    app: apache-drill
  type: NodePort
  ports:
    - port: 8047
      name: drill-ui
      nodePort: 30210
    - port: 31010
      name: drill-drillbit
      nodePort: 30220