qp:
  mill:
    backend:
      calcite:
        connection:
          model: ../etc/data/datasets/airlines/model-csv.yaml
      security:
        enabled: true
        providers:
          - type: file
            path: ./backend-calcite/etc/config/default/passwd.yaml