
qp:
  mill:
    backend:
      calcite:
        connection:
          model: ../etc/data/datasets/airlines/model-csv.yaml
      security:
        enabled: true
        providers:
          - type: file
            path: ./backend-calcite/etc/config/default/passwd.yaml
grpc:
  server:
    security:
      enabled: true
      certificate-chain: file:/home/vm/wip/qpointz/qpointz/sample/mill/mill-oauth/config/ssl/server.crt
      private-key: file:/home/vm/wip/qpointz/qpointz/sample/mill/mill-oauth/config/ssl/server.key

logging:
  level:
    root: debug