include:  
  - local : /.gitlab/.common.yml

stages:  
  - integration  

workflow:
  rules:
    - when : always

testIT:
  stage: integration
  extends: .gradle-job
  script:
    - echo $HOME
    - cd ${CI_PROJECT_DIR}/ai
    - ./gradlew --no-daemon --console plain testIT    