-- WI-317: Unified ai_chat schema — merge ai_chat_metadata + ai_conversation into ai_chat;
-- rename ai_conversation_turn → ai_chat_turn; conversation_id → chat_id on satellite tables.
-- Orphan conversations without metadata get user_id = 'default' (mill.ai.chat.default-user-id).

-- Phase 1: create new parent and turn tables (legacy tables untouched)

CREATE TABLE ai_chat (
    chat_id             VARCHAR(255) PRIMARY KEY,
    user_id             VARCHAR(255) NOT NULL,
    profile_id          VARCHAR(255) NOT NULL,
    chat_name           VARCHAR(512) NOT NULL,
    chat_type           VARCHAR(64)  NOT NULL,
    is_favorite         BOOLEAN      NOT NULL DEFAULT FALSE,
    context_type        VARCHAR(255),
    context_id          VARCHAR(255),
    context_label       VARCHAR(512),
    context_entity_type VARCHAR(255),
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP    NOT NULL
);

CREATE INDEX idx_ai_chat_user ON ai_chat (user_id);

CREATE UNIQUE INDEX uq_ai_chat_context ON ai_chat (user_id, context_type, context_id);

CREATE TABLE ai_chat_turn (
    turn_id     VARCHAR(255)  PRIMARY KEY,
    chat_id     VARCHAR(255)  NOT NULL,
    profile_id  VARCHAR(255)  NOT NULL,
    role        VARCHAR(32)   NOT NULL,
    text        TEXT,
    position    INT           NOT NULL,
    urn         VARCHAR(1024) NOT NULL,
    created_at  TIMESTAMP     NOT NULL
);

CREATE INDEX idx_ai_chat_turn_chat ON ai_chat_turn (chat_id, position);

-- Phase 2: copy parent rows into ai_chat

INSERT INTO ai_chat (
    chat_id, user_id, profile_id, chat_name, chat_type, is_favorite,
    context_type, context_id, context_label, context_entity_type,
    created_at, updated_at
)
SELECT
    m.chat_id,
    m.user_id,
    COALESCE(m.profile_id, c.profile_id),
    m.chat_name,
    m.chat_type,
    m.is_favorite,
    m.context_type,
    m.context_id,
    m.context_label,
    m.context_entity_type,
    COALESCE(m.created_at, c.created_at),
    GREATEST(m.updated_at, COALESCE(c.updated_at, m.updated_at))
FROM ai_chat_metadata m
LEFT JOIN ai_conversation c ON c.conversation_id = m.chat_id;

INSERT INTO ai_chat (
    chat_id, user_id, profile_id, chat_name, chat_type, is_favorite,
    created_at, updated_at
)
SELECT
    c.conversation_id,
    'default',
    c.profile_id,
    'Recovered Chat',
    'general',
    FALSE,
    c.created_at,
    c.updated_at
FROM ai_conversation c
WHERE NOT EXISTS (
    SELECT 1 FROM ai_chat_metadata m WHERE m.chat_id = c.conversation_id
);

-- Phase 3: copy turns into ai_chat_turn

INSERT INTO ai_chat_turn (
    turn_id, chat_id, profile_id, role, text, position, urn, created_at
)
SELECT
    t.turn_id,
    t.conversation_id,
    ch.profile_id,
    t.role,
    t.text,
    t.position,
    t.urn,
    t.created_at
FROM ai_conversation_turn t
INNER JOIN ai_chat ch ON ch.chat_id = t.conversation_id;

ALTER TABLE ai_chat_turn
    ADD CONSTRAINT fk_ai_chat_turn_chat
    FOREIGN KEY (chat_id) REFERENCES ai_chat (chat_id) ON DELETE CASCADE;

-- Phase 4: rebuild chat_memory tables with chat_id (portable H2 + Postgres)

CREATE TABLE chat_memory_new (
    chat_id      VARCHAR(255) PRIMARY KEY,
    profile_id   VARCHAR(255) NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);

INSERT INTO chat_memory_new (chat_id, profile_id, updated_at)
SELECT conversation_id, profile_id, updated_at FROM chat_memory;

CREATE TABLE chat_memory_message_new (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id      VARCHAR(255) NOT NULL,
    position     INT          NOT NULL,
    role         VARCHAR(32)  NOT NULL,
    content      TEXT         NOT NULL,
    tool_call_id VARCHAR(255),
    tool_name    VARCHAR(255)
);

INSERT INTO chat_memory_message_new (chat_id, position, role, content, tool_call_id, tool_name)
SELECT conversation_id, position, role, content, tool_call_id, tool_name FROM chat_memory_message;

DROP TABLE chat_memory_message;
DROP TABLE chat_memory;

ALTER TABLE chat_memory_new RENAME TO chat_memory;
ALTER TABLE chat_memory_message_new RENAME TO chat_memory_message;

ALTER TABLE chat_memory_message
    ADD CONSTRAINT fk_chat_memory_message_chat
    FOREIGN KEY (chat_id) REFERENCES chat_memory (chat_id) ON DELETE CASCADE;

CREATE INDEX idx_chat_memory_profile ON chat_memory (profile_id);
CREATE INDEX idx_chat_memory_message_chat ON chat_memory_message (chat_id, position);

-- Phase 4b: rename conversation_id → chat_id on other satellite tables

ALTER TABLE ai_artifact RENAME COLUMN conversation_id TO chat_id;
ALTER TABLE ai_active_artifact_pointer RENAME COLUMN conversation_id TO chat_id;
ALTER TABLE ai_run_event RENAME COLUMN conversation_id TO chat_id;

DROP INDEX IF EXISTS idx_ai_artifact_conv;
CREATE INDEX idx_ai_artifact_chat ON ai_artifact (chat_id, created_at);

DROP INDEX IF EXISTS idx_ai_run_event_conv;
CREATE INDEX idx_ai_run_event_chat ON ai_run_event (chat_id, created_at);

-- Phase 5: drop legacy transcript and metadata tables

DROP TABLE ai_conversation_turn;
DROP TABLE ai_conversation;
DROP TABLE ai_chat_metadata;
