-- V13__metadata_content.sql — authoring support content (WI-356 / metadata-authoring-profiles stage 1).

CREATE TABLE metadata_content (
    content_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               VARCHAR(36)  NOT NULL,
    content_urn        VARCHAR(512) NOT NULL,
    content_kind       VARCHAR(64)  NOT NULL,
    target_urn         VARCHAR(512) NOT NULL,
    scope_urn          VARCHAR(512),
    title              VARCHAR(512),
    description        TEXT,
    content_body       TEXT         NOT NULL,
    media_type         VARCHAR(128) NOT NULL DEFAULT 'application/json',
    sort_order         INTEGER      NOT NULL DEFAULT 0,
    enabled            BOOLEAN      NOT NULL DEFAULT TRUE,
    schema_version     VARCHAR(32),
    created_at         TIMESTAMP    NOT NULL,
    created_by         VARCHAR(255),
    last_modified_at   TIMESTAMP    NOT NULL,
    last_modified_by   VARCHAR(255),
    CONSTRAINT uq_metadata_content_urn UNIQUE (content_urn),
    CONSTRAINT uq_metadata_content_uuid UNIQUE (uuid)
);

CREATE INDEX idx_metadata_content_target_kind ON metadata_content (target_urn, content_kind);
