-- Mill persistence baseline schema.
-- Lane-specific migrations (chat memory, events, artifacts, etc.)
-- will add their own versioned scripts.

CREATE TABLE IF NOT EXISTS mill_schema_info (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lane        VARCHAR(64)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
