-- AI v3 baseline schema.
-- Chat memory, run events, transcript, artifacts, relations, and active pointers.

-- Lane 3: Chat Memory

CREATE TABLE chat_memory (
    conversation_id VARCHAR(255) PRIMARY KEY,
    profile_id      VARCHAR(255) NOT NULL,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_chat_memory_profile ON chat_memory (profile_id);

CREATE TABLE chat_memory_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL REFERENCES chat_memory (conversation_id) ON DELETE CASCADE,
    position        INT          NOT NULL,
    role            VARCHAR(32)  NOT NULL,
    content         TEXT         NOT NULL,
    tool_call_id    VARCHAR(255),
    tool_name       VARCHAR(255)
);

CREATE INDEX idx_chat_memory_message_conv ON chat_memory_message (conversation_id, position);

-- Routed run event log

CREATE TABLE ai_run_event (
    event_id        VARCHAR(255) PRIMARY KEY,
    run_id          VARCHAR(255) NOT NULL,
    conversation_id VARCHAR(255),
    profile_id      VARCHAR(255) NOT NULL,
    runtime_type    VARCHAR(255) NOT NULL,
    kind            VARCHAR(255) NOT NULL,
    content_json    TEXT         NOT NULL,
    created_at      TIMESTAMP    NOT NULL
);

CREATE INDEX idx_ai_run_event_conv ON ai_run_event (conversation_id, created_at);
CREATE INDEX idx_ai_run_event_run  ON ai_run_event (run_id, created_at);

-- Canonical chat transcript

CREATE TABLE ai_conversation (
    conversation_id VARCHAR(255) PRIMARY KEY,
    profile_id      VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);

CREATE TABLE ai_conversation_turn (
    turn_id         VARCHAR(255)  PRIMARY KEY,
    conversation_id VARCHAR(255)  NOT NULL REFERENCES ai_conversation (conversation_id) ON DELETE CASCADE,
    role            VARCHAR(32)   NOT NULL,
    text            TEXT,
    position        INT           NOT NULL,
    urn             VARCHAR(1024) NOT NULL,
    created_at      TIMESTAMP     NOT NULL
);

CREATE INDEX idx_ai_conversation_turn_conv ON ai_conversation_turn (conversation_id, position);

-- Artifact history

CREATE TABLE ai_artifact (
    artifact_id       VARCHAR(255)  PRIMARY KEY,
    conversation_id   VARCHAR(255)  NOT NULL,
    run_id            VARCHAR(255),
    turn_id           VARCHAR(255),
    kind              VARCHAR(255)  NOT NULL,
    payload_json      TEXT          NOT NULL,
    pointer_keys_json TEXT          NOT NULL,
    urn               VARCHAR(1024) NOT NULL,
    created_at        TIMESTAMP     NOT NULL
);

CREATE INDEX idx_ai_artifact_conv ON ai_artifact (conversation_id, created_at);
CREATE INDEX idx_ai_artifact_turn ON ai_artifact (turn_id);

-- Cross-model relation records

CREATE TABLE relation_record (
    relation_id   VARCHAR(255)  PRIMARY KEY,
    relation_kind VARCHAR(255)  NOT NULL,
    source_id     VARCHAR(255)  NOT NULL,
    source_type   VARCHAR(255)  NOT NULL,
    source_urn    VARCHAR(1024) NOT NULL,
    target_id     VARCHAR(255)  NOT NULL,
    target_type   VARCHAR(255)  NOT NULL,
    target_urn    VARCHAR(1024) NOT NULL,
    metadata_json TEXT,
    created_at    TIMESTAMP     NOT NULL
);

CREATE UNIQUE INDEX uq_relation_record_kind_source_target
    ON relation_record (relation_kind, source_id, target_id);

CREATE INDEX idx_relation_record_source ON relation_record (source_type, source_id);
CREATE INDEX idx_relation_record_target ON relation_record (target_type, target_id);

-- Active artifact pointers

CREATE TABLE ai_active_artifact_pointer (
    conversation_id VARCHAR(255) NOT NULL,
    pointer_key     VARCHAR(255) NOT NULL,
    artifact_id     VARCHAR(255) NOT NULL REFERENCES ai_artifact (artifact_id) ON DELETE CASCADE,
    updated_at      TIMESTAMP    NOT NULL,
    PRIMARY KEY (conversation_id, pointer_key)
);
