-- V4: Metadata relational persistence.
-- Facet type keys and scope keys use Mill URN notation (urn:mill/metadata/*).

CREATE TABLE metadata_scope (
    scope_id     VARCHAR(255) PRIMARY KEY,
    scope_type   VARCHAR(32)  NOT NULL,
    reference_id VARCHAR(255),
    display_name VARCHAR(512),
    owner_id     VARCHAR(255),
    visibility   VARCHAR(32)  NOT NULL DEFAULT 'PUBLIC',
    created_at   TIMESTAMP    NOT NULL
);
CREATE UNIQUE INDEX uq_metadata_scope_type_ref ON metadata_scope (scope_type, reference_id);
INSERT INTO metadata_scope (scope_id, scope_type, reference_id, display_name, owner_id, visibility, created_at)
VALUES ('urn:mill/metadata/scope:global', 'GLOBAL', NULL, 'Global', NULL, 'PUBLIC', CURRENT_TIMESTAMP);

CREATE TABLE metadata_entity (
    entity_id      VARCHAR(255) PRIMARY KEY,
    entity_type    VARCHAR(64)  NOT NULL,
    schema_name    VARCHAR(512),
    table_name     VARCHAR(512),
    attribute_name VARCHAR(512),
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255)
);
CREATE INDEX idx_metadata_entity_type ON metadata_entity (entity_type);
CREATE UNIQUE INDEX uq_metadata_entity_location
    ON metadata_entity (schema_name, table_name, attribute_name);

CREATE TABLE metadata_facet_scope (
    facet_scope_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id      VARCHAR(255) NOT NULL REFERENCES metadata_entity (entity_id) ON DELETE CASCADE,
    facet_type     VARCHAR(255) NOT NULL,
    scope_id       VARCHAR(255) NOT NULL REFERENCES metadata_scope (scope_id) ON DELETE CASCADE,
    payload_json   TEXT         NOT NULL DEFAULT '{}',
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    CONSTRAINT uq_metadata_facet_scope UNIQUE (entity_id, facet_type, scope_id)
);
CREATE INDEX idx_mfs_entity ON metadata_facet_scope (entity_id);
CREATE INDEX idx_mfs_facet  ON metadata_facet_scope (facet_type);
CREATE INDEX idx_mfs_scope  ON metadata_facet_scope (scope_id);

CREATE TABLE metadata_facet_type (
    type_key            VARCHAR(255) PRIMARY KEY,
    mandatory           BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled             BOOLEAN      NOT NULL DEFAULT TRUE,
    display_name        VARCHAR(512),
    description         TEXT,
    applicable_to_json  TEXT         NOT NULL DEFAULT '[]',
    version             VARCHAR(64),
    content_schema_json TEXT,
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP    NOT NULL,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255)
);

-- Seed: platform facet types with URN keys and URN entity-type strings in applicable_to_json.
INSERT INTO metadata_facet_type
    (type_key, mandatory, enabled, display_name, description, applicable_to_json, version, created_at, updated_at)
VALUES
    ('urn:mill/metadata/facet-type:structural',
     TRUE, TRUE, 'Structural', 'Physical schema binding',
     '["urn:mill/metadata/entity-type:table","urn:mill/metadata/entity-type:attribute"]',
     '1.0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('urn:mill/metadata/facet-type:descriptive',
     TRUE, TRUE, 'Descriptive', 'Human-readable metadata',
     '["urn:mill/metadata/entity-type:schema","urn:mill/metadata/entity-type:table","urn:mill/metadata/entity-type:attribute"]',
     '1.0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('urn:mill/metadata/facet-type:relation',
     TRUE, TRUE, 'Relation', 'Cross-entity relationships',
     '["urn:mill/metadata/entity-type:table"]',
     '1.0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('urn:mill/metadata/facet-type:concept',
     FALSE, TRUE, 'Concept', 'Business concept definitions',
     '["urn:mill/metadata/entity-type:concept"]',
     '1.0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('urn:mill/metadata/facet-type:value-mapping',
     FALSE, TRUE, 'Value Mapping', 'Attribute value mappings for NL-to-SQL',
     '["urn:mill/metadata/entity-type:attribute"]',
     '1.0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

CREATE TABLE metadata_promotion (
    promotion_id    VARCHAR(255) PRIMARY KEY,
    entity_id       VARCHAR(255) NOT NULL REFERENCES metadata_entity (entity_id) ON DELETE CASCADE,
    facet_type      VARCHAR(255) NOT NULL,
    source_scope_id VARCHAR(255) NOT NULL REFERENCES metadata_scope (scope_id),
    target_scope_id VARCHAR(255) NOT NULL REFERENCES metadata_scope (scope_id),
    status          VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    requested_by    VARCHAR(255) NOT NULL,
    reviewed_by     VARCHAR(255),
    requested_at    TIMESTAMP    NOT NULL,
    reviewed_at     TIMESTAMP,
    notes           TEXT
);
CREATE INDEX idx_mp_entity ON metadata_promotion (entity_id, facet_type);
CREATE INDEX idx_mp_status ON metadata_promotion (status);

-- Operation audit log.
CREATE TABLE metadata_operation_audit (
    audit_id        VARCHAR(255) PRIMARY KEY,
    operation_type  VARCHAR(32)  NOT NULL,
    entity_id       VARCHAR(255),
    facet_type      VARCHAR(255),
    scope_key       VARCHAR(512),
    actor_id        VARCHAR(255) NOT NULL,
    occurred_at     TIMESTAMP    NOT NULL,
    payload_before  TEXT,
    payload_after   TEXT,
    change_summary  VARCHAR(1024)
);
CREATE INDEX idx_moa_entity    ON metadata_operation_audit (entity_id);
CREATE INDEX idx_moa_actor     ON metadata_operation_audit (actor_id);
CREATE INDEX idx_moa_occurred  ON metadata_operation_audit (occurred_at);
CREATE INDEX idx_moa_operation ON metadata_operation_audit (operation_type);
