-- WI-174: golden-source embedding catalog + value rows.
-- TEXT/BYTEA: valid PostgreSQL; H2 testIT uses MODE=PostgreSQL (see application.yml in consuming modules).

CREATE TABLE ai_embedding_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_fingerprint VARCHAR(512) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    model_id VARCHAR(256) NOT NULL,
    dimension INT NOT NULL,
    params_json TEXT,
    label VARCHAR(256),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_embedding_model_fingerprint UNIQUE (config_fingerprint)
);

CREATE TABLE ai_value_mapping (
    stable_id UUID NOT NULL PRIMARY KEY,
    attribute_urn VARCHAR(1024) NOT NULL,
    content VARCHAR(8192) NOT NULL,
    content_hash VARCHAR(128),
    embedding BYTEA,
    metadata_json TEXT,
    embedding_model_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_value_mapping_model FOREIGN KEY (embedding_model_id) REFERENCES ai_embedding_model (id) ON DELETE RESTRICT,
    CONSTRAINT uq_ai_value_mapping_attr_content UNIQUE (attribute_urn, content)
);

CREATE INDEX idx_ai_value_mapping_attribute ON ai_value_mapping (attribute_urn);
CREATE INDEX idx_ai_value_mapping_model ON ai_value_mapping (embedding_model_id);
