-- V8: Normalize metadata facet persistence for row-per-instance storage.
-- Introduces:
--   - metadata_facet_type_def (renamed from metadata_facet_type)
--   - metadata_facet_type (runtime/observed facet types)
--   - metadata_facet (facet payload instances)
-- while keeping existing API/business keys intact.

-- Canonical definitions table rename.
ALTER TABLE metadata_facet_type RENAME TO metadata_facet_type_def;

-- Runtime/observed facet types.
CREATE TABLE metadata_facet_type (
    facet_type_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_key           VARCHAR(255) NOT NULL,
    slug               VARCHAR(255),
    display_name       VARCHAR(512),
    description        TEXT,
    source             VARCHAR(32)  NOT NULL DEFAULT 'OBSERVED',
    facet_type_def_key VARCHAR(255) REFERENCES metadata_facet_type_def(type_key),
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    created_by         VARCHAR(255),
    updated_by         VARCHAR(255)
);
CREATE UNIQUE INDEX uq_metadata_facet_type_key ON metadata_facet_type(type_key);
CREATE INDEX idx_metadata_facet_type_slug ON metadata_facet_type(slug);
CREATE INDEX idx_metadata_facet_type_def_key ON metadata_facet_type(facet_type_def_key);

-- Facet payload instances (row-per-instance).
CREATE TABLE metadata_facet (
    facet_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id      VARCHAR(255) NOT NULL REFERENCES metadata_entity(entity_id) ON DELETE CASCADE,
    scope_id       VARCHAR(255) NOT NULL REFERENCES metadata_scope(scope_id) ON DELETE CASCADE,
    facet_type_id  BIGINT       NOT NULL REFERENCES metadata_facet_type(facet_type_id),
    payload_json   TEXT         NOT NULL DEFAULT '{}',
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255)
);
CREATE INDEX idx_metadata_facet_entity ON metadata_facet(entity_id);
CREATE INDEX idx_metadata_facet_scope ON metadata_facet(scope_id);
CREATE INDEX idx_metadata_facet_type ON metadata_facet(facet_type_id);

-- Seed runtime type rows from canonical definitions first.
INSERT INTO metadata_facet_type (
    type_key, slug, display_name, description, source, facet_type_def_key, created_at, updated_at, created_by, updated_by
)
SELECT
    d.type_key,
    d.type_key,
    d.display_name,
    d.description,
    'DEFINED',
    d.type_key,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'system',
    'system'
FROM metadata_facet_type_def d;

-- Include any observed facet types present in historical scope rows.
INSERT INTO metadata_facet_type (
    type_key, slug, display_name, description, source, facet_type_def_key, created_at, updated_at, created_by, updated_by
)
SELECT
    s.facet_type,
    s.facet_type,
    NULL,
    NULL,
    'OBSERVED',
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'system',
    'system'
FROM (
    SELECT DISTINCT facet_type
    FROM metadata_facet_scope
) s
LEFT JOIN metadata_facet_type t ON t.type_key = s.facet_type
WHERE t.facet_type_id IS NULL;

-- Migrate existing scope rows into row-per-instance table.
INSERT INTO metadata_facet (
    entity_id, scope_id, facet_type_id, payload_json, created_at, updated_at, created_by, updated_by
)
SELECT
    mfs.entity_id,
    mfs.scope_id,
    ft.facet_type_id,
    mfs.payload_json,
    mfs.created_at,
    mfs.updated_at,
    mfs.created_by,
    mfs.updated_by
FROM metadata_facet_scope mfs
JOIN metadata_facet_type ft ON ft.type_key = mfs.facet_type;

