dump:
  in:
    root_dir: C:\\Users\\vm\\wip\\qpointz\\qpointz\\mill
  actions:
    - move_package:
        from: io.qpointz.mill
        to: com.tras.bas.yuki
    - delete_dir:
        paths:
          - clients/mill-py/millclient/proto/io
          - clients/mill-spark
          - clients/etc/mill-test
    - delete_file:
        paths:
          - clients/mill-py/protoc.txt
          - clients/mill-py/gen.sh
          - .sdkmanrc
          - .gitlab-ci.yml
          - clients/.gitlab-ci.yml
    - delete_empty_folder:
    - replace_in_files:
        exts:  [".java", ".py", ".kt", ".kts", ".Driver", ".proto", ".json"]
        replace:
          - old: io.qpointz.mill
            new: com.tras.bas.yuki
          - old: io.qpointz
            new: com.tras.bas.yuki
          - old: qpointz.io
            new: tras.com
          - old: qpointz
            new: yuki
    - move_dir:
        from: mill-azure-service-function
        to: yuki-azure-service-function
    - move_dir:
        from: mill-backends
        to: yuki-backends
    - move_dir:
        from: mill-common
        to: yuki-common
    - move_dir:
        from: mill-common-service
        to: yuki-common-service
    - move_dir:
        from: mill-common-security
        to: yuki-common-security
    - move_dir:
        from: mill-grpc-service
        to: yuki-grpc-service
    - move_dir:
        from: mill-service
        to: yuki-service
    - move_dir:
        from: mill-sample-service
        to: yuki-sample-service
    - move_dir:
        from: clients/mill-jdbc-driver
        to: clients/yuki-jdbc-driver
    - move_dir:
        from: clients/mill-jdbc-shell
        to: clients/yuki-jdbc-shell
    - delete_dir:
        paths:
          - mill-azure-service-function
          - mill-backends
          - mill-common
          - mill-common-service
          - mill-grpc-service
          - mill-sample-service
          - mill-service
    - replace_in_files:
        exts: [ ".kt", ".kts" ]
        replace:
          - old: ":mill-azure-service-function"
            new: ":yuki-azure-service-function"
          - old: ":mill-starter-backends"
            new: ":yuki-starter-backends"
          - old: ":mill-common"
            new: ":yuki-common"
          - old: ":mill-common-service"
            new: ":yuki-common-service"
          - old: ":mill-starter-grpc-service"
            new: ":yuki-starter-grpc-service"
          - old: ":mill-service"
            new: ":yuki-service"
          - old: ":mill-service"
            new: ":yuki-service"
          - old: ":mill-sample-service"
            new: ":yuki-sample-service"
          - old: ":clients:mill-jdbc-driver"
            new: ":clients:yuki-jdbc-driver"
          - old: ":clients:mill-jdbc-shell"
            new: ":clients:yuki-jdbc-shell"