/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "mill"


include (":core:mill-core")
include (":core:mill-security-core")
include (":core:mill-service-core")

include (":mill-test-common")

include (":clients:mill-jdbc-driver")
include (":clients:mill-jdbc-shell")

include (":mill-starter-backends")
include (":mill-service")

include (":services:mill-jet-grpc-service")
include (":services:mill-jet-http-service")
include (":services:mill-starter-services")

include (":ai:mill-ai-core")
include (":ai:mill-ai-nlsql-chat-service")
include (":services:mill-grinder-service")

include (":services:mill-ai-llm-service")
include (":services:mill-ai-mcp-service")


dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

pluginManagement {
    includeBuild("build-logic")

    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }

    plugins {
        kotlin("jvm") version "1.9.23"
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
}
